/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiV1BibleThemeBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get bible versions
 */
export type getApiV1BibleVersionsResponse200 = {
  data: void
  status: 200
}

export type getApiV1BibleVersionsResponseSuccess = (getApiV1BibleVersionsResponse200) & {
  headers: Headers;
};
;

export type getApiV1BibleVersionsResponse = (getApiV1BibleVersionsResponseSuccess)

export const getGetApiV1BibleVersionsUrl = () => {




  return `/api/v1/bible/versions`
}

export const getApiV1BibleVersions = async ( options?: RequestInit): Promise<getApiV1BibleVersionsResponse> => {

  return holyricsInstance<getApiV1BibleVersionsResponse>(getGetApiV1BibleVersionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BibleVersionsQueryKey = () => {
    return [
    `/api/v1/bible/versions`
    ] as const;
    }


export const getGetApiV1BibleVersionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BibleVersionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BibleVersions>>> = ({ signal }) => getApiV1BibleVersions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BibleVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BibleVersions>>>
export type GetApiV1BibleVersionsQueryError = unknown


export function useGetApiV1BibleVersions<TData = Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BibleVersions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BibleVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BibleVersions<TData = Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BibleVersions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BibleVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BibleVersions<TData = Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BibleVersions<TData = Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersions>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BibleVersionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get bible versions (v2)
 */
export type getApiV1BibleVersionsV2Response200 = {
  data: void
  status: 200
}

export type getApiV1BibleVersionsV2ResponseSuccess = (getApiV1BibleVersionsV2Response200) & {
  headers: Headers;
};
;

export type getApiV1BibleVersionsV2Response = (getApiV1BibleVersionsV2ResponseSuccess)

export const getGetApiV1BibleVersionsV2Url = () => {




  return `/api/v1/bible/versions-v2`
}

export const getApiV1BibleVersionsV2 = async ( options?: RequestInit): Promise<getApiV1BibleVersionsV2Response> => {

  return holyricsInstance<getApiV1BibleVersionsV2Response>(getGetApiV1BibleVersionsV2Url(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BibleVersionsV2QueryKey = () => {
    return [
    `/api/v1/bible/versions-v2`
    ] as const;
    }


export const getGetApiV1BibleVersionsV2QueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BibleVersionsV2QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>> = ({ signal }) => getApiV1BibleVersionsV2({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BibleVersionsV2QueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>>
export type GetApiV1BibleVersionsV2QueryError = unknown


export function useGetApiV1BibleVersionsV2<TData = Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BibleVersionsV2<TData = Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BibleVersionsV2<TData = Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BibleVersionsV2<TData = Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleVersionsV2>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BibleVersionsV2QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get bible settings
 */
export type getApiV1BibleSettingsResponse200 = {
  data: void
  status: 200
}

export type getApiV1BibleSettingsResponseSuccess = (getApiV1BibleSettingsResponse200) & {
  headers: Headers;
};
;

export type getApiV1BibleSettingsResponse = (getApiV1BibleSettingsResponseSuccess)

export const getGetApiV1BibleSettingsUrl = () => {




  return `/api/v1/bible/settings`
}

export const getApiV1BibleSettings = async ( options?: RequestInit): Promise<getApiV1BibleSettingsResponse> => {

  return holyricsInstance<getApiV1BibleSettingsResponse>(getGetApiV1BibleSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BibleSettingsQueryKey = () => {
    return [
    `/api/v1/bible/settings`
    ] as const;
    }


export const getGetApiV1BibleSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BibleSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BibleSettings>>> = ({ signal }) => getApiV1BibleSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BibleSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BibleSettings>>>
export type GetApiV1BibleSettingsQueryError = unknown


export function useGetApiV1BibleSettings<TData = Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BibleSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BibleSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BibleSettings<TData = Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BibleSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BibleSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BibleSettings<TData = Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BibleSettings<TData = Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BibleSettings>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BibleSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set bible settings
 */
export type postApiV1BibleSettingsResponse200 = {
  data: void
  status: 200
}

export type postApiV1BibleSettingsResponseSuccess = (postApiV1BibleSettingsResponse200) & {
  headers: Headers;
};
;

export type postApiV1BibleSettingsResponse = (postApiV1BibleSettingsResponseSuccess)

export const getPostApiV1BibleSettingsUrl = () => {




  return `/api/v1/bible/settings`
}

export const postApiV1BibleSettings = async (postApiV1BibleSettingsBody: unknown, options?: RequestInit): Promise<postApiV1BibleSettingsResponse> => {

  return holyricsInstance<postApiV1BibleSettingsResponse>(getPostApiV1BibleSettingsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1BibleSettingsBody,)
  }
);}




export const getPostApiV1BibleSettingsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BibleSettings>>, TError,{data: unknown}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BibleSettings>>, TError,{data: unknown}, TContext> => {

const mutationKey = ['postApiV1BibleSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BibleSettings>>, {data: unknown}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BibleSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BibleSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BibleSettings>>>
    export type PostApiV1BibleSettingsMutationBody = unknown
    export type PostApiV1BibleSettingsMutationError = unknown

    export const usePostApiV1BibleSettings = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BibleSettings>>, TError,{data: unknown}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BibleSettings>>,
        TError,
        {data: unknown},
        TContext
      > => {
      return useMutation(getPostApiV1BibleSettingsMutationOptions(options), queryClient);
    }
    /**
 * Set bible theme
 */
export type postApiV1BibleThemeResponse200 = {
  data: unknown
  status: 200
}

export type postApiV1BibleThemeResponseSuccess = (postApiV1BibleThemeResponse200) & {
  headers: Headers;
};
;

export type postApiV1BibleThemeResponse = (postApiV1BibleThemeResponseSuccess)

export const getPostApiV1BibleThemeUrl = () => {




  return `/api/v1/bible/theme`
}

export const postApiV1BibleTheme = async (postApiV1BibleThemeBody: PostApiV1BibleThemeBody, options?: RequestInit): Promise<postApiV1BibleThemeResponse> => {

  return holyricsInstance<postApiV1BibleThemeResponse>(getPostApiV1BibleThemeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1BibleThemeBody,)
  }
);}




export const getPostApiV1BibleThemeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BibleTheme>>, TError,{data: PostApiV1BibleThemeBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BibleTheme>>, TError,{data: PostApiV1BibleThemeBody}, TContext> => {

const mutationKey = ['postApiV1BibleTheme'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BibleTheme>>, {data: PostApiV1BibleThemeBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BibleTheme(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BibleThemeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BibleTheme>>>
    export type PostApiV1BibleThemeMutationBody = PostApiV1BibleThemeBody
    export type PostApiV1BibleThemeMutationError = unknown

    export const usePostApiV1BibleTheme = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BibleTheme>>, TError,{data: PostApiV1BibleThemeBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BibleTheme>>,
        TError,
        {data: PostApiV1BibleThemeBody},
        TContext
      > => {
      return useMutation(getPostApiV1BibleThemeMutationOptions(options), queryClient);
    }
