/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiV1PresentationAlertBody,
  PostApiV1PresentationF10Body,
  PostApiV1PresentationF8Body,
  PostApiV1PresentationF9Body,
  PostApiV1PresentationGoToDescriptionBody,
  PostApiV1PresentationGoToIndexBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get current presentation info
 */
export type getApiV1PresentationCurrentResponse200 = {
  data: void
  status: 200
}

export type getApiV1PresentationCurrentResponseSuccess = (getApiV1PresentationCurrentResponse200) & {
  headers: Headers;
};
;

export type getApiV1PresentationCurrentResponse = (getApiV1PresentationCurrentResponseSuccess)

export const getGetApiV1PresentationCurrentUrl = () => {




  return `/api/v1/presentation/current`
}

export const getApiV1PresentationCurrent = async ( options?: RequestInit): Promise<getApiV1PresentationCurrentResponse> => {

  return holyricsInstance<getApiV1PresentationCurrentResponse>(getGetApiV1PresentationCurrentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PresentationCurrentQueryKey = () => {
    return [
    `/api/v1/presentation/current`
    ] as const;
    }


export const getGetApiV1PresentationCurrentQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PresentationCurrentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PresentationCurrent>>> = ({ signal }) => getApiV1PresentationCurrent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PresentationCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PresentationCurrent>>>
export type GetApiV1PresentationCurrentQueryError = unknown


export function useGetApiV1PresentationCurrent<TData = Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationCurrent<TData = Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationCurrent<TData = Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PresentationCurrent<TData = Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PresentationCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Close current presentation
 */
export type postApiV1PresentationCloseResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationCloseResponseSuccess = (postApiV1PresentationCloseResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationCloseResponse = (postApiV1PresentationCloseResponseSuccess)

export const getPostApiV1PresentationCloseUrl = () => {




  return `/api/v1/presentation/close`
}

export const postApiV1PresentationClose = async ( options?: RequestInit): Promise<postApiV1PresentationCloseResponse> => {

  return holyricsInstance<postApiV1PresentationCloseResponse>(getPostApiV1PresentationCloseUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1PresentationCloseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationClose>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationClose>>, TError,void, TContext> => {

const mutationKey = ['postApiV1PresentationClose'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationClose>>, void> = () => {


          return  postApiV1PresentationClose(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationCloseMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationClose>>>

    export type PostApiV1PresentationCloseMutationError = unknown

    export const usePostApiV1PresentationClose = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationClose>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationClose>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1PresentationCloseMutationOptions(options), queryClient);
    }
    /**
 * Get Logo (F8) status
 */
export type getApiV1PresentationF8Response200 = {
  data: void
  status: 200
}

export type getApiV1PresentationF8ResponseSuccess = (getApiV1PresentationF8Response200) & {
  headers: Headers;
};
;

export type getApiV1PresentationF8Response = (getApiV1PresentationF8ResponseSuccess)

export const getGetApiV1PresentationF8Url = () => {




  return `/api/v1/presentation/f8`
}

export const getApiV1PresentationF8 = async ( options?: RequestInit): Promise<getApiV1PresentationF8Response> => {

  return holyricsInstance<getApiV1PresentationF8Response>(getGetApiV1PresentationF8Url(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PresentationF8QueryKey = () => {
    return [
    `/api/v1/presentation/f8`
    ] as const;
    }


export const getGetApiV1PresentationF8QueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PresentationF8QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PresentationF8>>> = ({ signal }) => getApiV1PresentationF8({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PresentationF8QueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PresentationF8>>>
export type GetApiV1PresentationF8QueryError = unknown


export function useGetApiV1PresentationF8<TData = Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationF8>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationF8>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationF8<TData = Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationF8>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationF8>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationF8<TData = Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PresentationF8<TData = Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF8>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PresentationF8QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set Logo (F8) status
 */
export type postApiV1PresentationF8Response200 = {
  data: void
  status: 200
}

export type postApiV1PresentationF8ResponseSuccess = (postApiV1PresentationF8Response200) & {
  headers: Headers;
};
;

export type postApiV1PresentationF8Response = (postApiV1PresentationF8ResponseSuccess)

export const getPostApiV1PresentationF8Url = () => {




  return `/api/v1/presentation/f8`
}

export const postApiV1PresentationF8 = async (postApiV1PresentationF8Body: PostApiV1PresentationF8Body, options?: RequestInit): Promise<postApiV1PresentationF8Response> => {

  return holyricsInstance<postApiV1PresentationF8Response>(getPostApiV1PresentationF8Url(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PresentationF8Body,)
  }
);}




export const getPostApiV1PresentationF8MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF8>>, TError,{data: PostApiV1PresentationF8Body}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF8>>, TError,{data: PostApiV1PresentationF8Body}, TContext> => {

const mutationKey = ['postApiV1PresentationF8'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationF8>>, {data: PostApiV1PresentationF8Body}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PresentationF8(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationF8MutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationF8>>>
    export type PostApiV1PresentationF8MutationBody = PostApiV1PresentationF8Body
    export type PostApiV1PresentationF8MutationError = unknown

    export const usePostApiV1PresentationF8 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF8>>, TError,{data: PostApiV1PresentationF8Body}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationF8>>,
        TError,
        {data: PostApiV1PresentationF8Body},
        TContext
      > => {
      return useMutation(getPostApiV1PresentationF8MutationOptions(options), queryClient);
    }
    /**
 * Toggle Logo (F8) status
 */
export type postApiV1PresentationF8ToggleResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationF8ToggleResponseSuccess = (postApiV1PresentationF8ToggleResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationF8ToggleResponse = (postApiV1PresentationF8ToggleResponseSuccess)

export const getPostApiV1PresentationF8ToggleUrl = () => {




  return `/api/v1/presentation/f8/toggle`
}

export const postApiV1PresentationF8Toggle = async ( options?: RequestInit): Promise<postApiV1PresentationF8ToggleResponse> => {

  return holyricsInstance<postApiV1PresentationF8ToggleResponse>(getPostApiV1PresentationF8ToggleUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1PresentationF8ToggleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF8Toggle>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF8Toggle>>, TError,void, TContext> => {

const mutationKey = ['postApiV1PresentationF8Toggle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationF8Toggle>>, void> = () => {


          return  postApiV1PresentationF8Toggle(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationF8ToggleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationF8Toggle>>>

    export type PostApiV1PresentationF8ToggleMutationError = unknown

    export const usePostApiV1PresentationF8Toggle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF8Toggle>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationF8Toggle>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1PresentationF8ToggleMutationOptions(options), queryClient);
    }
    /**
 * Get No Lyrics (F9) status
 */
export type getApiV1PresentationF9Response200 = {
  data: void
  status: 200
}

export type getApiV1PresentationF9ResponseSuccess = (getApiV1PresentationF9Response200) & {
  headers: Headers;
};
;

export type getApiV1PresentationF9Response = (getApiV1PresentationF9ResponseSuccess)

export const getGetApiV1PresentationF9Url = () => {




  return `/api/v1/presentation/f9`
}

export const getApiV1PresentationF9 = async ( options?: RequestInit): Promise<getApiV1PresentationF9Response> => {

  return holyricsInstance<getApiV1PresentationF9Response>(getGetApiV1PresentationF9Url(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PresentationF9QueryKey = () => {
    return [
    `/api/v1/presentation/f9`
    ] as const;
    }


export const getGetApiV1PresentationF9QueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PresentationF9QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PresentationF9>>> = ({ signal }) => getApiV1PresentationF9({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PresentationF9QueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PresentationF9>>>
export type GetApiV1PresentationF9QueryError = unknown


export function useGetApiV1PresentationF9<TData = Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationF9>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationF9>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationF9<TData = Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationF9>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationF9>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationF9<TData = Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PresentationF9<TData = Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF9>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PresentationF9QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set No Lyrics (F9) status
 */
export type postApiV1PresentationF9Response200 = {
  data: void
  status: 200
}

export type postApiV1PresentationF9ResponseSuccess = (postApiV1PresentationF9Response200) & {
  headers: Headers;
};
;

export type postApiV1PresentationF9Response = (postApiV1PresentationF9ResponseSuccess)

export const getPostApiV1PresentationF9Url = () => {




  return `/api/v1/presentation/f9`
}

export const postApiV1PresentationF9 = async (postApiV1PresentationF9Body: PostApiV1PresentationF9Body, options?: RequestInit): Promise<postApiV1PresentationF9Response> => {

  return holyricsInstance<postApiV1PresentationF9Response>(getPostApiV1PresentationF9Url(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PresentationF9Body,)
  }
);}




export const getPostApiV1PresentationF9MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF9>>, TError,{data: PostApiV1PresentationF9Body}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF9>>, TError,{data: PostApiV1PresentationF9Body}, TContext> => {

const mutationKey = ['postApiV1PresentationF9'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationF9>>, {data: PostApiV1PresentationF9Body}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PresentationF9(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationF9MutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationF9>>>
    export type PostApiV1PresentationF9MutationBody = PostApiV1PresentationF9Body
    export type PostApiV1PresentationF9MutationError = unknown

    export const usePostApiV1PresentationF9 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF9>>, TError,{data: PostApiV1PresentationF9Body}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationF9>>,
        TError,
        {data: PostApiV1PresentationF9Body},
        TContext
      > => {
      return useMutation(getPostApiV1PresentationF9MutationOptions(options), queryClient);
    }
    /**
 * Toggle No Lyrics (F9) status
 */
export type postApiV1PresentationF9ToggleResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationF9ToggleResponseSuccess = (postApiV1PresentationF9ToggleResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationF9ToggleResponse = (postApiV1PresentationF9ToggleResponseSuccess)

export const getPostApiV1PresentationF9ToggleUrl = () => {




  return `/api/v1/presentation/f9/toggle`
}

export const postApiV1PresentationF9Toggle = async ( options?: RequestInit): Promise<postApiV1PresentationF9ToggleResponse> => {

  return holyricsInstance<postApiV1PresentationF9ToggleResponse>(getPostApiV1PresentationF9ToggleUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1PresentationF9ToggleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF9Toggle>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF9Toggle>>, TError,void, TContext> => {

const mutationKey = ['postApiV1PresentationF9Toggle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationF9Toggle>>, void> = () => {


          return  postApiV1PresentationF9Toggle(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationF9ToggleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationF9Toggle>>>

    export type PostApiV1PresentationF9ToggleMutationError = unknown

    export const usePostApiV1PresentationF9Toggle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF9Toggle>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationF9Toggle>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1PresentationF9ToggleMutationOptions(options), queryClient);
    }
    /**
 * Get Black Screen (F10) status
 */
export type getApiV1PresentationF10Response200 = {
  data: void
  status: 200
}

export type getApiV1PresentationF10ResponseSuccess = (getApiV1PresentationF10Response200) & {
  headers: Headers;
};
;

export type getApiV1PresentationF10Response = (getApiV1PresentationF10ResponseSuccess)

export const getGetApiV1PresentationF10Url = () => {




  return `/api/v1/presentation/f10`
}

export const getApiV1PresentationF10 = async ( options?: RequestInit): Promise<getApiV1PresentationF10Response> => {

  return holyricsInstance<getApiV1PresentationF10Response>(getGetApiV1PresentationF10Url(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PresentationF10QueryKey = () => {
    return [
    `/api/v1/presentation/f10`
    ] as const;
    }


export const getGetApiV1PresentationF10QueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PresentationF10QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PresentationF10>>> = ({ signal }) => getApiV1PresentationF10({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PresentationF10QueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PresentationF10>>>
export type GetApiV1PresentationF10QueryError = unknown


export function useGetApiV1PresentationF10<TData = Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationF10>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationF10>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationF10<TData = Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationF10>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationF10>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationF10<TData = Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PresentationF10<TData = Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationF10>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PresentationF10QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set Black Screen (F10) status
 */
export type postApiV1PresentationF10Response200 = {
  data: void
  status: 200
}

export type postApiV1PresentationF10ResponseSuccess = (postApiV1PresentationF10Response200) & {
  headers: Headers;
};
;

export type postApiV1PresentationF10Response = (postApiV1PresentationF10ResponseSuccess)

export const getPostApiV1PresentationF10Url = () => {




  return `/api/v1/presentation/f10`
}

export const postApiV1PresentationF10 = async (postApiV1PresentationF10Body: PostApiV1PresentationF10Body, options?: RequestInit): Promise<postApiV1PresentationF10Response> => {

  return holyricsInstance<postApiV1PresentationF10Response>(getPostApiV1PresentationF10Url(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PresentationF10Body,)
  }
);}




export const getPostApiV1PresentationF10MutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF10>>, TError,{data: PostApiV1PresentationF10Body}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF10>>, TError,{data: PostApiV1PresentationF10Body}, TContext> => {

const mutationKey = ['postApiV1PresentationF10'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationF10>>, {data: PostApiV1PresentationF10Body}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PresentationF10(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationF10MutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationF10>>>
    export type PostApiV1PresentationF10MutationBody = PostApiV1PresentationF10Body
    export type PostApiV1PresentationF10MutationError = unknown

    export const usePostApiV1PresentationF10 = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF10>>, TError,{data: PostApiV1PresentationF10Body}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationF10>>,
        TError,
        {data: PostApiV1PresentationF10Body},
        TContext
      > => {
      return useMutation(getPostApiV1PresentationF10MutationOptions(options), queryClient);
    }
    /**
 * Toggle Black Screen (F10) status
 */
export type postApiV1PresentationF10ToggleResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationF10ToggleResponseSuccess = (postApiV1PresentationF10ToggleResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationF10ToggleResponse = (postApiV1PresentationF10ToggleResponseSuccess)

export const getPostApiV1PresentationF10ToggleUrl = () => {




  return `/api/v1/presentation/f10/toggle`
}

export const postApiV1PresentationF10Toggle = async ( options?: RequestInit): Promise<postApiV1PresentationF10ToggleResponse> => {

  return holyricsInstance<postApiV1PresentationF10ToggleResponse>(getPostApiV1PresentationF10ToggleUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1PresentationF10ToggleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF10Toggle>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF10Toggle>>, TError,void, TContext> => {

const mutationKey = ['postApiV1PresentationF10Toggle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationF10Toggle>>, void> = () => {


          return  postApiV1PresentationF10Toggle(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationF10ToggleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationF10Toggle>>>

    export type PostApiV1PresentationF10ToggleMutationError = unknown

    export const usePostApiV1PresentationF10Toggle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationF10Toggle>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationF10Toggle>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1PresentationF10ToggleMutationOptions(options), queryClient);
    }
    /**
 * Go to next slide
 */
export type postApiV1PresentationNextResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationNextResponseSuccess = (postApiV1PresentationNextResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationNextResponse = (postApiV1PresentationNextResponseSuccess)

export const getPostApiV1PresentationNextUrl = () => {




  return `/api/v1/presentation/next`
}

export const postApiV1PresentationNext = async ( options?: RequestInit): Promise<postApiV1PresentationNextResponse> => {

  return holyricsInstance<postApiV1PresentationNextResponse>(getPostApiV1PresentationNextUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1PresentationNextMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationNext>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationNext>>, TError,void, TContext> => {

const mutationKey = ['postApiV1PresentationNext'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationNext>>, void> = () => {


          return  postApiV1PresentationNext(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationNextMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationNext>>>

    export type PostApiV1PresentationNextMutationError = unknown

    export const usePostApiV1PresentationNext = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationNext>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationNext>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1PresentationNextMutationOptions(options), queryClient);
    }
    /**
 * Go to previous slide
 */
export type postApiV1PresentationPreviousResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationPreviousResponseSuccess = (postApiV1PresentationPreviousResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationPreviousResponse = (postApiV1PresentationPreviousResponseSuccess)

export const getPostApiV1PresentationPreviousUrl = () => {




  return `/api/v1/presentation/previous`
}

export const postApiV1PresentationPrevious = async ( options?: RequestInit): Promise<postApiV1PresentationPreviousResponse> => {

  return holyricsInstance<postApiV1PresentationPreviousResponse>(getPostApiV1PresentationPreviousUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1PresentationPreviousMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationPrevious>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationPrevious>>, TError,void, TContext> => {

const mutationKey = ['postApiV1PresentationPrevious'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationPrevious>>, void> = () => {


          return  postApiV1PresentationPrevious(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationPreviousMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationPrevious>>>

    export type PostApiV1PresentationPreviousMutationError = unknown

    export const usePostApiV1PresentationPrevious = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationPrevious>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationPrevious>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1PresentationPreviousMutationOptions(options), queryClient);
    }
    /**
 * Go to slide by index
 */
export type postApiV1PresentationGoToIndexResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationGoToIndexResponseSuccess = (postApiV1PresentationGoToIndexResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationGoToIndexResponse = (postApiV1PresentationGoToIndexResponseSuccess)

export const getPostApiV1PresentationGoToIndexUrl = () => {




  return `/api/v1/presentation/go-to-index`
}

export const postApiV1PresentationGoToIndex = async (postApiV1PresentationGoToIndexBody: PostApiV1PresentationGoToIndexBody, options?: RequestInit): Promise<postApiV1PresentationGoToIndexResponse> => {

  return holyricsInstance<postApiV1PresentationGoToIndexResponse>(getPostApiV1PresentationGoToIndexUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PresentationGoToIndexBody,)
  }
);}




export const getPostApiV1PresentationGoToIndexMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationGoToIndex>>, TError,{data: PostApiV1PresentationGoToIndexBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationGoToIndex>>, TError,{data: PostApiV1PresentationGoToIndexBody}, TContext> => {

const mutationKey = ['postApiV1PresentationGoToIndex'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationGoToIndex>>, {data: PostApiV1PresentationGoToIndexBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PresentationGoToIndex(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationGoToIndexMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationGoToIndex>>>
    export type PostApiV1PresentationGoToIndexMutationBody = PostApiV1PresentationGoToIndexBody
    export type PostApiV1PresentationGoToIndexMutationError = unknown

    export const usePostApiV1PresentationGoToIndex = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationGoToIndex>>, TError,{data: PostApiV1PresentationGoToIndexBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationGoToIndex>>,
        TError,
        {data: PostApiV1PresentationGoToIndexBody},
        TContext
      > => {
      return useMutation(getPostApiV1PresentationGoToIndexMutationOptions(options), queryClient);
    }
    /**
 * Get descriptions for all slides in current presentation
 */
export type getApiV1PresentationSlideDescriptionsResponse200 = {
  data: void
  status: 200
}

export type getApiV1PresentationSlideDescriptionsResponseSuccess = (getApiV1PresentationSlideDescriptionsResponse200) & {
  headers: Headers;
};
;

export type getApiV1PresentationSlideDescriptionsResponse = (getApiV1PresentationSlideDescriptionsResponseSuccess)

export const getGetApiV1PresentationSlideDescriptionsUrl = () => {




  return `/api/v1/presentation/slide-descriptions`
}

export const getApiV1PresentationSlideDescriptions = async ( options?: RequestInit): Promise<getApiV1PresentationSlideDescriptionsResponse> => {

  return holyricsInstance<getApiV1PresentationSlideDescriptionsResponse>(getGetApiV1PresentationSlideDescriptionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PresentationSlideDescriptionsQueryKey = () => {
    return [
    `/api/v1/presentation/slide-descriptions`
    ] as const;
    }


export const getGetApiV1PresentationSlideDescriptionsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PresentationSlideDescriptionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>> = ({ signal }) => getApiV1PresentationSlideDescriptions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PresentationSlideDescriptionsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>>
export type GetApiV1PresentationSlideDescriptionsQueryError = unknown


export function useGetApiV1PresentationSlideDescriptions<TData = Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationSlideDescriptions<TData = Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationSlideDescriptions<TData = Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PresentationSlideDescriptions<TData = Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationSlideDescriptions>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PresentationSlideDescriptionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Go to slide by description
 */
export type postApiV1PresentationGoToDescriptionResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationGoToDescriptionResponseSuccess = (postApiV1PresentationGoToDescriptionResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationGoToDescriptionResponse = (postApiV1PresentationGoToDescriptionResponseSuccess)

export const getPostApiV1PresentationGoToDescriptionUrl = () => {




  return `/api/v1/presentation/go-to-description`
}

export const postApiV1PresentationGoToDescription = async (postApiV1PresentationGoToDescriptionBody: PostApiV1PresentationGoToDescriptionBody, options?: RequestInit): Promise<postApiV1PresentationGoToDescriptionResponse> => {

  return holyricsInstance<postApiV1PresentationGoToDescriptionResponse>(getPostApiV1PresentationGoToDescriptionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PresentationGoToDescriptionBody,)
  }
);}




export const getPostApiV1PresentationGoToDescriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationGoToDescription>>, TError,{data: PostApiV1PresentationGoToDescriptionBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationGoToDescription>>, TError,{data: PostApiV1PresentationGoToDescriptionBody}, TContext> => {

const mutationKey = ['postApiV1PresentationGoToDescription'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationGoToDescription>>, {data: PostApiV1PresentationGoToDescriptionBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PresentationGoToDescription(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationGoToDescriptionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationGoToDescription>>>
    export type PostApiV1PresentationGoToDescriptionMutationBody = PostApiV1PresentationGoToDescriptionBody
    export type PostApiV1PresentationGoToDescriptionMutationError = unknown

    export const usePostApiV1PresentationGoToDescription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationGoToDescription>>, TError,{data: PostApiV1PresentationGoToDescriptionBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationGoToDescription>>,
        TError,
        {data: PostApiV1PresentationGoToDescriptionBody},
        TContext
      > => {
      return useMutation(getPostApiV1PresentationGoToDescriptionMutationOptions(options), queryClient);
    }
    /**
 * Get current alert status
 */
export type getApiV1PresentationAlertResponse200 = {
  data: void
  status: 200
}

export type getApiV1PresentationAlertResponseSuccess = (getApiV1PresentationAlertResponse200) & {
  headers: Headers;
};
;

export type getApiV1PresentationAlertResponse = (getApiV1PresentationAlertResponseSuccess)

export const getGetApiV1PresentationAlertUrl = () => {




  return `/api/v1/presentation/alert`
}

export const getApiV1PresentationAlert = async ( options?: RequestInit): Promise<getApiV1PresentationAlertResponse> => {

  return holyricsInstance<getApiV1PresentationAlertResponse>(getGetApiV1PresentationAlertUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PresentationAlertQueryKey = () => {
    return [
    `/api/v1/presentation/alert`
    ] as const;
    }


export const getGetApiV1PresentationAlertQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PresentationAlertQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PresentationAlert>>> = ({ signal }) => getApiV1PresentationAlert({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PresentationAlertQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PresentationAlert>>>
export type GetApiV1PresentationAlertQueryError = unknown


export function useGetApiV1PresentationAlert<TData = Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationAlert>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationAlert>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationAlert<TData = Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PresentationAlert>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PresentationAlert>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PresentationAlert<TData = Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PresentationAlert<TData = Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PresentationAlert>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PresentationAlertQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set alert on screen
 */
export type postApiV1PresentationAlertResponse200 = {
  data: void
  status: 200
}

export type postApiV1PresentationAlertResponseSuccess = (postApiV1PresentationAlertResponse200) & {
  headers: Headers;
};
;

export type postApiV1PresentationAlertResponse = (postApiV1PresentationAlertResponseSuccess)

export const getPostApiV1PresentationAlertUrl = () => {




  return `/api/v1/presentation/alert`
}

export const postApiV1PresentationAlert = async (postApiV1PresentationAlertBody: PostApiV1PresentationAlertBody, options?: RequestInit): Promise<postApiV1PresentationAlertResponse> => {

  return holyricsInstance<postApiV1PresentationAlertResponse>(getPostApiV1PresentationAlertUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PresentationAlertBody,)
  }
);}




export const getPostApiV1PresentationAlertMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationAlert>>, TError,{data: PostApiV1PresentationAlertBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationAlert>>, TError,{data: PostApiV1PresentationAlertBody}, TContext> => {

const mutationKey = ['postApiV1PresentationAlert'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PresentationAlert>>, {data: PostApiV1PresentationAlertBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PresentationAlert(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PresentationAlertMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PresentationAlert>>>
    export type PostApiV1PresentationAlertMutationBody = PostApiV1PresentationAlertBody
    export type PostApiV1PresentationAlertMutationError = unknown

    export const usePostApiV1PresentationAlert = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PresentationAlert>>, TError,{data: PostApiV1PresentationAlertBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PresentationAlert>>,
        TError,
        {data: PostApiV1PresentationAlertBody},
        TContext
      > => {
      return useMutation(getPostApiV1PresentationAlertMutationOptions(options), queryClient);
    }
