/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1ActionsScriptBody = {
  script_id: string;
  action: string;
  [key: string]: unknown;
};
