/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1TextsSelectVerseBody = {
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  book: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  chapter: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  verse: number;
};
