/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1SchedulesShowBody = {
  id?: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  index?: number;
  type?: string;
  song_id?: string;
};
