/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiV1CommunicationPanelAlertBody,
  PostApiV1CommunicationPanelCountdownStartBody,
  PostApiV1CommunicationPanelTextBody,
  PostApiV1CommunicationPanelTimerStartBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get communication panel info
 */
export type getApiV1CommunicationPanelInfoResponse200 = {
  data: void
  status: 200
}

export type getApiV1CommunicationPanelInfoResponseSuccess = (getApiV1CommunicationPanelInfoResponse200) & {
  headers: Headers;
};
;

export type getApiV1CommunicationPanelInfoResponse = (getApiV1CommunicationPanelInfoResponseSuccess)

export const getGetApiV1CommunicationPanelInfoUrl = () => {




  return `/api/v1/communication-panel/info`
}

export const getApiV1CommunicationPanelInfo = async ( options?: RequestInit): Promise<getApiV1CommunicationPanelInfoResponse> => {

  return holyricsInstance<getApiV1CommunicationPanelInfoResponse>(getGetApiV1CommunicationPanelInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1CommunicationPanelInfoQueryKey = () => {
    return [
    `/api/v1/communication-panel/info`
    ] as const;
    }


export const getGetApiV1CommunicationPanelInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1CommunicationPanelInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>> = ({ signal }) => getApiV1CommunicationPanelInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1CommunicationPanelInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>>
export type GetApiV1CommunicationPanelInfoQueryError = unknown


export function useGetApiV1CommunicationPanelInfo<TData = Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CommunicationPanelInfo<TData = Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1CommunicationPanelInfo<TData = Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1CommunicationPanelInfo<TData = Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1CommunicationPanelInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1CommunicationPanelInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set communication panel settings
 */
export type postApiV1CommunicationPanelSettingsResponse200 = {
  data: void
  status: 200
}

export type postApiV1CommunicationPanelSettingsResponseSuccess = (postApiV1CommunicationPanelSettingsResponse200) & {
  headers: Headers;
};
;

export type postApiV1CommunicationPanelSettingsResponse = (postApiV1CommunicationPanelSettingsResponseSuccess)

export const getPostApiV1CommunicationPanelSettingsUrl = () => {




  return `/api/v1/communication-panel/settings`
}

export const postApiV1CommunicationPanelSettings = async (postApiV1CommunicationPanelSettingsBody: unknown, options?: RequestInit): Promise<postApiV1CommunicationPanelSettingsResponse> => {

  return holyricsInstance<postApiV1CommunicationPanelSettingsResponse>(getPostApiV1CommunicationPanelSettingsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1CommunicationPanelSettingsBody,)
  }
);}




export const getPostApiV1CommunicationPanelSettingsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelSettings>>, TError,{data: unknown}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelSettings>>, TError,{data: unknown}, TContext> => {

const mutationKey = ['postApiV1CommunicationPanelSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommunicationPanelSettings>>, {data: unknown}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CommunicationPanelSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommunicationPanelSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommunicationPanelSettings>>>
    export type PostApiV1CommunicationPanelSettingsMutationBody = unknown
    export type PostApiV1CommunicationPanelSettingsMutationError = unknown

    export const usePostApiV1CommunicationPanelSettings = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelSettings>>, TError,{data: unknown}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommunicationPanelSettings>>,
        TError,
        {data: unknown},
        TContext
      > => {
      return useMutation(getPostApiV1CommunicationPanelSettingsMutationOptions(options), queryClient);
    }
    /**
 * Start countdown in communication panel
 */
export type postApiV1CommunicationPanelCountdownStartResponse200 = {
  data: void
  status: 200
}

export type postApiV1CommunicationPanelCountdownStartResponseSuccess = (postApiV1CommunicationPanelCountdownStartResponse200) & {
  headers: Headers;
};
;

export type postApiV1CommunicationPanelCountdownStartResponse = (postApiV1CommunicationPanelCountdownStartResponseSuccess)

export const getPostApiV1CommunicationPanelCountdownStartUrl = () => {




  return `/api/v1/communication-panel/countdown/start`
}

export const postApiV1CommunicationPanelCountdownStart = async (postApiV1CommunicationPanelCountdownStartBody: PostApiV1CommunicationPanelCountdownStartBody, options?: RequestInit): Promise<postApiV1CommunicationPanelCountdownStartResponse> => {

  return holyricsInstance<postApiV1CommunicationPanelCountdownStartResponse>(getPostApiV1CommunicationPanelCountdownStartUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1CommunicationPanelCountdownStartBody,)
  }
);}




export const getPostApiV1CommunicationPanelCountdownStartMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStart>>, TError,{data: PostApiV1CommunicationPanelCountdownStartBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStart>>, TError,{data: PostApiV1CommunicationPanelCountdownStartBody}, TContext> => {

const mutationKey = ['postApiV1CommunicationPanelCountdownStart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStart>>, {data: PostApiV1CommunicationPanelCountdownStartBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CommunicationPanelCountdownStart(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommunicationPanelCountdownStartMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStart>>>
    export type PostApiV1CommunicationPanelCountdownStartMutationBody = PostApiV1CommunicationPanelCountdownStartBody
    export type PostApiV1CommunicationPanelCountdownStartMutationError = unknown

    export const usePostApiV1CommunicationPanelCountdownStart = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStart>>, TError,{data: PostApiV1CommunicationPanelCountdownStartBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStart>>,
        TError,
        {data: PostApiV1CommunicationPanelCountdownStartBody},
        TContext
      > => {
      return useMutation(getPostApiV1CommunicationPanelCountdownStartMutationOptions(options), queryClient);
    }
    /**
 * Stop countdown in communication panel
 */
export type postApiV1CommunicationPanelCountdownStopResponse200 = {
  data: void
  status: 200
}

export type postApiV1CommunicationPanelCountdownStopResponseSuccess = (postApiV1CommunicationPanelCountdownStopResponse200) & {
  headers: Headers;
};
;

export type postApiV1CommunicationPanelCountdownStopResponse = (postApiV1CommunicationPanelCountdownStopResponseSuccess)

export const getPostApiV1CommunicationPanelCountdownStopUrl = () => {




  return `/api/v1/communication-panel/countdown/stop`
}

export const postApiV1CommunicationPanelCountdownStop = async ( options?: RequestInit): Promise<postApiV1CommunicationPanelCountdownStopResponse> => {

  return holyricsInstance<postApiV1CommunicationPanelCountdownStopResponse>(getPostApiV1CommunicationPanelCountdownStopUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1CommunicationPanelCountdownStopMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStop>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStop>>, TError,void, TContext> => {

const mutationKey = ['postApiV1CommunicationPanelCountdownStop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStop>>, void> = () => {


          return  postApiV1CommunicationPanelCountdownStop(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommunicationPanelCountdownStopMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStop>>>

    export type PostApiV1CommunicationPanelCountdownStopMutationError = unknown

    export const usePostApiV1CommunicationPanelCountdownStop = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStop>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommunicationPanelCountdownStop>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1CommunicationPanelCountdownStopMutationOptions(options), queryClient);
    }
    /**
 * Start timer in communication panel
 */
export type postApiV1CommunicationPanelTimerStartResponse200 = {
  data: void
  status: 200
}

export type postApiV1CommunicationPanelTimerStartResponseSuccess = (postApiV1CommunicationPanelTimerStartResponse200) & {
  headers: Headers;
};
;

export type postApiV1CommunicationPanelTimerStartResponse = (postApiV1CommunicationPanelTimerStartResponseSuccess)

export const getPostApiV1CommunicationPanelTimerStartUrl = () => {




  return `/api/v1/communication-panel/timer/start`
}

export const postApiV1CommunicationPanelTimerStart = async (postApiV1CommunicationPanelTimerStartBody: PostApiV1CommunicationPanelTimerStartBody, options?: RequestInit): Promise<postApiV1CommunicationPanelTimerStartResponse> => {

  return holyricsInstance<postApiV1CommunicationPanelTimerStartResponse>(getPostApiV1CommunicationPanelTimerStartUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1CommunicationPanelTimerStartBody,)
  }
);}




export const getPostApiV1CommunicationPanelTimerStartMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStart>>, TError,{data: PostApiV1CommunicationPanelTimerStartBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStart>>, TError,{data: PostApiV1CommunicationPanelTimerStartBody}, TContext> => {

const mutationKey = ['postApiV1CommunicationPanelTimerStart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStart>>, {data: PostApiV1CommunicationPanelTimerStartBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CommunicationPanelTimerStart(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommunicationPanelTimerStartMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStart>>>
    export type PostApiV1CommunicationPanelTimerStartMutationBody = PostApiV1CommunicationPanelTimerStartBody
    export type PostApiV1CommunicationPanelTimerStartMutationError = unknown

    export const usePostApiV1CommunicationPanelTimerStart = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStart>>, TError,{data: PostApiV1CommunicationPanelTimerStartBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStart>>,
        TError,
        {data: PostApiV1CommunicationPanelTimerStartBody},
        TContext
      > => {
      return useMutation(getPostApiV1CommunicationPanelTimerStartMutationOptions(options), queryClient);
    }
    /**
 * Stop timer in communication panel
 */
export type postApiV1CommunicationPanelTimerStopResponse200 = {
  data: void
  status: 200
}

export type postApiV1CommunicationPanelTimerStopResponseSuccess = (postApiV1CommunicationPanelTimerStopResponse200) & {
  headers: Headers;
};
;

export type postApiV1CommunicationPanelTimerStopResponse = (postApiV1CommunicationPanelTimerStopResponseSuccess)

export const getPostApiV1CommunicationPanelTimerStopUrl = () => {




  return `/api/v1/communication-panel/timer/stop`
}

export const postApiV1CommunicationPanelTimerStop = async ( options?: RequestInit): Promise<postApiV1CommunicationPanelTimerStopResponse> => {

  return holyricsInstance<postApiV1CommunicationPanelTimerStopResponse>(getPostApiV1CommunicationPanelTimerStopUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1CommunicationPanelTimerStopMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStop>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStop>>, TError,void, TContext> => {

const mutationKey = ['postApiV1CommunicationPanelTimerStop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStop>>, void> = () => {


          return  postApiV1CommunicationPanelTimerStop(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommunicationPanelTimerStopMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStop>>>

    export type PostApiV1CommunicationPanelTimerStopMutationError = unknown

    export const usePostApiV1CommunicationPanelTimerStop = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStop>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommunicationPanelTimerStop>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1CommunicationPanelTimerStopMutationOptions(options), queryClient);
    }
    /**
 * Set text in communication panel
 */
export type postApiV1CommunicationPanelTextResponse200 = {
  data: void
  status: 200
}

export type postApiV1CommunicationPanelTextResponseSuccess = (postApiV1CommunicationPanelTextResponse200) & {
  headers: Headers;
};
;

export type postApiV1CommunicationPanelTextResponse = (postApiV1CommunicationPanelTextResponseSuccess)

export const getPostApiV1CommunicationPanelTextUrl = () => {




  return `/api/v1/communication-panel/text`
}

export const postApiV1CommunicationPanelText = async (postApiV1CommunicationPanelTextBody: PostApiV1CommunicationPanelTextBody, options?: RequestInit): Promise<postApiV1CommunicationPanelTextResponse> => {

  return holyricsInstance<postApiV1CommunicationPanelTextResponse>(getPostApiV1CommunicationPanelTextUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1CommunicationPanelTextBody,)
  }
);}




export const getPostApiV1CommunicationPanelTextMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelText>>, TError,{data: PostApiV1CommunicationPanelTextBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelText>>, TError,{data: PostApiV1CommunicationPanelTextBody}, TContext> => {

const mutationKey = ['postApiV1CommunicationPanelText'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommunicationPanelText>>, {data: PostApiV1CommunicationPanelTextBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CommunicationPanelText(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommunicationPanelTextMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommunicationPanelText>>>
    export type PostApiV1CommunicationPanelTextMutationBody = PostApiV1CommunicationPanelTextBody
    export type PostApiV1CommunicationPanelTextMutationError = unknown

    export const usePostApiV1CommunicationPanelText = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelText>>, TError,{data: PostApiV1CommunicationPanelTextBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommunicationPanelText>>,
        TError,
        {data: PostApiV1CommunicationPanelTextBody},
        TContext
      > => {
      return useMutation(getPostApiV1CommunicationPanelTextMutationOptions(options), queryClient);
    }
    /**
 * Set alert in communication panel
 */
export type postApiV1CommunicationPanelAlertResponse200 = {
  data: void
  status: 200
}

export type postApiV1CommunicationPanelAlertResponseSuccess = (postApiV1CommunicationPanelAlertResponse200) & {
  headers: Headers;
};
;

export type postApiV1CommunicationPanelAlertResponse = (postApiV1CommunicationPanelAlertResponseSuccess)

export const getPostApiV1CommunicationPanelAlertUrl = () => {




  return `/api/v1/communication-panel/alert`
}

export const postApiV1CommunicationPanelAlert = async (postApiV1CommunicationPanelAlertBody: PostApiV1CommunicationPanelAlertBody, options?: RequestInit): Promise<postApiV1CommunicationPanelAlertResponse> => {

  return holyricsInstance<postApiV1CommunicationPanelAlertResponse>(getPostApiV1CommunicationPanelAlertUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1CommunicationPanelAlertBody,)
  }
);}




export const getPostApiV1CommunicationPanelAlertMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelAlert>>, TError,{data: PostApiV1CommunicationPanelAlertBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelAlert>>, TError,{data: PostApiV1CommunicationPanelAlertBody}, TContext> => {

const mutationKey = ['postApiV1CommunicationPanelAlert'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommunicationPanelAlert>>, {data: PostApiV1CommunicationPanelAlertBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CommunicationPanelAlert(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommunicationPanelAlertMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommunicationPanelAlert>>>
    export type PostApiV1CommunicationPanelAlertMutationBody = PostApiV1CommunicationPanelAlertBody
    export type PostApiV1CommunicationPanelAlertMutationError = unknown

    export const usePostApiV1CommunicationPanelAlert = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelAlert>>, TError,{data: PostApiV1CommunicationPanelAlertBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommunicationPanelAlert>>,
        TError,
        {data: PostApiV1CommunicationPanelAlertBody},
        TContext
      > => {
      return useMutation(getPostApiV1CommunicationPanelAlertMutationOptions(options), queryClient);
    }
    /**
 * Call attention in communication panel
 */
export type postApiV1CommunicationPanelCallAttentionResponse200 = {
  data: void
  status: 200
}

export type postApiV1CommunicationPanelCallAttentionResponseSuccess = (postApiV1CommunicationPanelCallAttentionResponse200) & {
  headers: Headers;
};
;

export type postApiV1CommunicationPanelCallAttentionResponse = (postApiV1CommunicationPanelCallAttentionResponseSuccess)

export const getPostApiV1CommunicationPanelCallAttentionUrl = () => {




  return `/api/v1/communication-panel/call-attention`
}

export const postApiV1CommunicationPanelCallAttention = async ( options?: RequestInit): Promise<postApiV1CommunicationPanelCallAttentionResponse> => {

  return holyricsInstance<postApiV1CommunicationPanelCallAttentionResponse>(getPostApiV1CommunicationPanelCallAttentionUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1CommunicationPanelCallAttentionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCallAttention>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCallAttention>>, TError,void, TContext> => {

const mutationKey = ['postApiV1CommunicationPanelCallAttention'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CommunicationPanelCallAttention>>, void> = () => {


          return  postApiV1CommunicationPanelCallAttention(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CommunicationPanelCallAttentionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CommunicationPanelCallAttention>>>

    export type PostApiV1CommunicationPanelCallAttentionMutationError = unknown

    export const usePostApiV1CommunicationPanelCallAttention = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CommunicationPanelCallAttention>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CommunicationPanelCallAttention>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1CommunicationPanelCallAttentionMutationOptions(options), queryClient);
    }
