/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiV1MediaPlayerActionBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get media player info
 */
export type getApiV1MediaPlayerInfoResponse200 = {
  data: void
  status: 200
}

export type getApiV1MediaPlayerInfoResponseSuccess = (getApiV1MediaPlayerInfoResponse200) & {
  headers: Headers;
};
;

export type getApiV1MediaPlayerInfoResponse = (getApiV1MediaPlayerInfoResponseSuccess)

export const getGetApiV1MediaPlayerInfoUrl = () => {




  return `/api/v1/media-player/info`
}

export const getApiV1MediaPlayerInfo = async ( options?: RequestInit): Promise<getApiV1MediaPlayerInfoResponse> => {

  return holyricsInstance<getApiV1MediaPlayerInfoResponse>(getGetApiV1MediaPlayerInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1MediaPlayerInfoQueryKey = () => {
    return [
    `/api/v1/media-player/info`
    ] as const;
    }


export const getGetApiV1MediaPlayerInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1MediaPlayerInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>> = ({ signal }) => getApiV1MediaPlayerInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1MediaPlayerInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>>
export type GetApiV1MediaPlayerInfoQueryError = unknown


export function useGetApiV1MediaPlayerInfo<TData = Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MediaPlayerInfo<TData = Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1MediaPlayerInfo<TData = Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1MediaPlayerInfo<TData = Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1MediaPlayerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1MediaPlayerInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Perform media player action
 */
export type postApiV1MediaPlayerActionResponse200 = {
  data: void
  status: 200
}

export type postApiV1MediaPlayerActionResponseSuccess = (postApiV1MediaPlayerActionResponse200) & {
  headers: Headers;
};
;

export type postApiV1MediaPlayerActionResponse = (postApiV1MediaPlayerActionResponseSuccess)

export const getPostApiV1MediaPlayerActionUrl = () => {




  return `/api/v1/media-player/action`
}

export const postApiV1MediaPlayerAction = async (postApiV1MediaPlayerActionBody: PostApiV1MediaPlayerActionBody, options?: RequestInit): Promise<postApiV1MediaPlayerActionResponse> => {

  return holyricsInstance<postApiV1MediaPlayerActionResponse>(getPostApiV1MediaPlayerActionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1MediaPlayerActionBody,)
  }
);}




export const getPostApiV1MediaPlayerActionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1MediaPlayerAction>>, TError,{data: PostApiV1MediaPlayerActionBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1MediaPlayerAction>>, TError,{data: PostApiV1MediaPlayerActionBody}, TContext> => {

const mutationKey = ['postApiV1MediaPlayerAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1MediaPlayerAction>>, {data: PostApiV1MediaPlayerActionBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1MediaPlayerAction(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1MediaPlayerActionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1MediaPlayerAction>>>
    export type PostApiV1MediaPlayerActionMutationBody = PostApiV1MediaPlayerActionBody
    export type PostApiV1MediaPlayerActionMutationError = unknown

    export const usePostApiV1MediaPlayerAction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1MediaPlayerAction>>, TError,{data: PostApiV1MediaPlayerActionBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1MediaPlayerAction>>,
        TError,
        {data: PostApiV1MediaPlayerActionBody},
        TContext
      > => {
      return useMutation(getPostApiV1MediaPlayerActionMutationOptions(options), queryClient);
    }
