import type { BibleBook } from "@/lib/bible/types";

export const BIBLE_BOOKS: BibleBook[] = [
  { id: "genesis", order: 1, name: "Gênesis", shortName: "Gn", chapterCount: 50, testament: "old", aliases: ["genesis", "gn", "gen", "g"] },
  { id: "exodo", order: 2, name: "Êxodo", shortName: "Ex", chapterCount: 40, testament: "old", aliases: ["exodo", "êxodo", "ex", "exo"] },
  { id: "levitico", order: 3, name: "Levítico", shortName: "Lv", chapterCount: 27, testament: "old", aliases: ["levitico", "levítico", "lv", "lev"] },
  { id: "numeros", order: 4, name: "Números", shortName: "Nm", chapterCount: 36, testament: "old", aliases: ["numeros", "números", "nm", "num"] },
  { id: "deuteronomio", order: 5, name: "Deuteronômio", shortName: "Dt", chapterCount: 34, testament: "old", aliases: ["deuteronomio", "deuteronômio", "dt", "deut"] },
  { id: "josue", order: 6, name: "Josué", shortName: "Js", chapterCount: 24, testament: "old", aliases: ["josue", "josué", "js", "jos"] },
  { id: "juizes", order: 7, name: "Juízes", shortName: "Jz", chapterCount: 21, testament: "old", aliases: ["juizes", "juízes", "jz", "jui"] },
  { id: "rute", order: 8, name: "Rute", shortName: "Rt", chapterCount: 4, testament: "old", aliases: ["rute", "rt", "rut"] },
  { id: "1samuel", order: 9, name: "1 Samuel", shortName: "1Sm", chapterCount: 31, testament: "old", aliases: ["1samuel", "1 samuel", "1sm", "1 sm", "i samuel"] },
  { id: "2samuel", order: 10, name: "2 Samuel", shortName: "2Sm", chapterCount: 24, testament: "old", aliases: ["2samuel", "2 samuel", "2sm", "2 sm", "ii samuel"] },
  { id: "1reis", order: 11, name: "1 Reis", shortName: "1Rs", chapterCount: 22, testament: "old", aliases: ["1reis", "1 reis", "1rs", "1 rs", "i reis"] },
  { id: "2reis", order: 12, name: "2 Reis", shortName: "2Rs", chapterCount: 25, testament: "old", aliases: ["2reis", "2 reis", "2rs", "2 rs", "ii reis"] },
  { id: "1cronicas", order: 13, name: "1 Crônicas", shortName: "1Cr", chapterCount: 29, testament: "old", aliases: ["1cronicas", "1 crônicas", "1 crônicas", "1cr", "1 cr", "i cronicas"] },
  { id: "2cronicas", order: 14, name: "2 Crônicas", shortName: "2Cr", chapterCount: 36, testament: "old", aliases: ["2cronicas", "2 crônicas", "2 crônicas", "2cr", "2 cr", "ii cronicas"] },
  { id: "esdras", order: 15, name: "Esdras", shortName: "Ed", chapterCount: 10, testament: "old", aliases: ["esdras", "ed", "esd"] },
  { id: "neemias", order: 16, name: "Neemias", shortName: "Ne", chapterCount: 13, testament: "old", aliases: ["neemias", "ne", "nee"] },
  { id: "ester", order: 17, name: "Ester", shortName: "Et", chapterCount: 10, testament: "old", aliases: ["ester", "et", "est"] },
  { id: "jo", order: 18, name: "Jó", shortName: "Jó", chapterCount: 42, testament: "old", aliases: ["jo", "jó", "job"] },
  { id: "salmos", order: 19, name: "Salmos", shortName: "Sl", chapterCount: 150, testament: "old", aliases: ["salmos", "sl", "salmo", "ps"] },
  { id: "proverbios", order: 20, name: "Provérbios", shortName: "Pv", chapterCount: 31, testament: "old", aliases: ["proverbios", "provérbios", "pv", "prov"] },
  { id: "eclesiastes", order: 21, name: "Eclesiastes", shortName: "Ec", chapterCount: 12, testament: "old", aliases: ["eclesiastes", "ec", "ecl"] },
  { id: "cantares", order: 22, name: "Cantares", shortName: "Ct", chapterCount: 8, testament: "old", aliases: ["cantares", "ct", "canticos", "cânticos"] },
  { id: "isaias", order: 23, name: "Isaías", shortName: "Is", chapterCount: 66, testament: "old", aliases: ["isaias", "isaías", "is", "isa"] },
  { id: "jeremias", order: 24, name: "Jeremias", shortName: "Jr", chapterCount: 52, testament: "old", aliases: ["jeremias", "jr", "jer"] },
  { id: "lamentacoes", order: 25, name: "Lamentações", shortName: "Lm", chapterCount: 5, testament: "old", aliases: ["lamentacoes", "lamentações", "lm", "lam"] },
  { id: "ezequiel", order: 26, name: "Ezequiel", shortName: "Ez", chapterCount: 48, testament: "old", aliases: ["ezequiel", "ez", "eze"] },
  { id: "daniel", order: 27, name: "Daniel", shortName: "Dn", chapterCount: 12, testament: "old", aliases: ["daniel", "dn", "dan"] },
  { id: "oseias", order: 28, name: "Oséias", shortName: "Os", chapterCount: 14, testament: "old", aliases: ["oseias", "oséias", "os", "ose"] },
  { id: "joel", order: 29, name: "Joel", shortName: "Jl", chapterCount: 3, testament: "old", aliases: ["joel", "jl"] },
  { id: "amos", order: 30, name: "Amós", shortName: "Am", chapterCount: 9, testament: "old", aliases: ["amos", "amós", "am"] },
  { id: "obadias", order: 31, name: "Obadias", shortName: "Ob", chapterCount: 1, testament: "old", aliases: ["obadias", "ob"] },
  { id: "jonas", order: 32, name: "Jonas", shortName: "Jn", chapterCount: 4, testament: "old", aliases: ["jonas", "jn", "jon"] },
  { id: "miqueias", order: 33, name: "Miquéias", shortName: "Mq", chapterCount: 7, testament: "old", aliases: ["miqueias", "miquéias", "mq", "miq"] },
  { id: "naum", order: 34, name: "Naum", shortName: "Na", chapterCount: 3, testament: "old", aliases: ["naum", "na"] },
  { id: "habacuque", order: 35, name: "Habacuque", shortName: "Hc", chapterCount: 3, testament: "old", aliases: ["habacuque", "hc", "hab"] },
  { id: "sofonias", order: 36, name: "Sofonias", shortName: "Sf", chapterCount: 3, testament: "old", aliases: ["sofonias", "sf", "sof"] },
  { id: "ageu", order: 37, name: "Ageu", shortName: "Ag", chapterCount: 2, testament: "old", aliases: ["ageu", "ag"] },
  { id: "zacarias", order: 38, name: "Zacarias", shortName: "Zc", chapterCount: 14, testament: "old", aliases: ["zacarias", "zc", "zac"] },
  { id: "malaquias", order: 39, name: "Malaquias", shortName: "Ml", chapterCount: 4, testament: "old", aliases: ["malaquias", "ml", "mal"] },
  { id: "mateus", order: 40, name: "Mateus", shortName: "Mt", chapterCount: 28, testament: "new", aliases: ["mateus", "mt", "mat"] },
  { id: "marcos", order: 41, name: "Marcos", shortName: "Mc", chapterCount: 16, testament: "new", aliases: ["marcos", "mc", "mar"] },
  { id: "lucas", order: 42, name: "Lucas", shortName: "Lc", chapterCount: 24, testament: "new", aliases: ["lucas", "lc", "luc"] },
  { id: "joao", order: 43, name: "João", shortName: "Jo", chapterCount: 21, testament: "new", aliases: ["joao", "joão", "jo", "joh"] },
  { id: "atos", order: 44, name: "Atos", shortName: "At", chapterCount: 28, testament: "new", aliases: ["atos", "at"] },
  { id: "romanos", order: 45, name: "Romanos", shortName: "Rm", chapterCount: 16, testament: "new", aliases: ["romanos", "rm", "rom"] },
  { id: "1corintios", order: 46, name: "1 Coríntios", shortName: "1Co", chapterCount: 16, testament: "new", aliases: ["1corintios", "1 coríntios", "1cor", "1co", "i corintios"] },
  { id: "2corintios", order: 47, name: "2 Coríntios", shortName: "2Co", chapterCount: 13, testament: "new", aliases: ["2corintios", "2 coríntios", "2cor", "2co", "ii corintios"] },
  { id: "galatas", order: 48, name: "Gálatas", shortName: "Gl", chapterCount: 6, testament: "new", aliases: ["galatas", "gálatas", "gl", "gal"] },
  { id: "efesios", order: 49, name: "Efésios", shortName: "Ef", chapterCount: 6, testament: "new", aliases: ["efesios", "efésios", "ef", "efe"] },
  { id: "filipenses", order: 50, name: "Filipenses", shortName: "Fp", chapterCount: 4, testament: "new", aliases: ["filipenses", "fp", "fil"] },
  { id: "colossenses", order: 51, name: "Colossenses", shortName: "Cl", chapterCount: 4, testament: "new", aliases: ["colossenses", "cl", "col"] },
  { id: "1tessalonicenses", order: 52, name: "1 Tessalonicenses", shortName: "1Ts", chapterCount: 5, testament: "new", aliases: ["1tessalonicenses", "1 tessalonicenses", "1ts", "1 tes", "i tessalonicenses"] },
  { id: "2tessalonicenses", order: 53, name: "2 Tessalonicenses", shortName: "2Ts", chapterCount: 3, testament: "new", aliases: ["2tessalonicenses", "2 tessalonicenses", "2ts", "2 tes", "ii tessalonicenses"] },
  { id: "1timoteo", order: 54, name: "1 Timóteo", shortName: "1Tm", chapterCount: 6, testament: "new", aliases: ["1timoteo", "1 timóteo", "1tm", "1 tim", "i timoteo"] },
  { id: "2timoteo", order: 55, name: "2 Timóteo", shortName: "2Tm", chapterCount: 4, testament: "new", aliases: ["2timoteo", "2 timóteo", "2tm", "2 tim", "ii timoteo"] },
  { id: "tito", order: 56, name: "Tito", shortName: "Tt", chapterCount: 3, testament: "new", aliases: ["tito", "tt", "tit"] },
  { id: "filemom", order: 57, name: "Filemom", shortName: "Fm", chapterCount: 1, testament: "new", aliases: ["filemom", "fm", "film"] },
  { id: "hebreus", order: 58, name: "Hebreus", shortName: "Hb", chapterCount: 13, testament: "new", aliases: ["hebreus", "hb", "heb"] },
  { id: "tiago", order: 59, name: "Tiago", shortName: "Tg", chapterCount: 5, testament: "new", aliases: ["tiago", "tg", "tia"] },
  { id: "1pedro", order: 60, name: "1 Pedro", shortName: "1Pe", chapterCount: 5, testament: "new", aliases: ["1pedro", "1 pedro", "1pe", "1 pe", "i pedro"] },
  { id: "2pedro", order: 61, name: "2 Pedro", shortName: "2Pe", chapterCount: 3, testament: "new", aliases: ["2pedro", "2 pedro", "2pe", "2 pe", "ii pedro"] },
  { id: "1joao", order: 62, name: "1 João", shortName: "1Jo", chapterCount: 5, testament: "new", aliases: ["1joao", "1 joão", "1jo", "1 jo", "i joao"] },
  { id: "2joao", order: 63, name: "2 João", shortName: "2Jo", chapterCount: 1, testament: "new", aliases: ["2joao", "2 joão", "2jo", "2 jo", "ii joao"] },
  { id: "3joao", order: 64, name: "3 João", shortName: "3Jo", chapterCount: 1, testament: "new", aliases: ["3joao", "3 joão", "3jo", "3 jo", "iii joao"] },
  { id: "judas", order: 65, name: "Judas", shortName: "Jd", chapterCount: 1, testament: "new", aliases: ["judas", "jd", "jud"] },
  { id: "apocalipse", order: 66, name: "Apocalipse", shortName: "Ap", chapterCount: 22, testament: "new", aliases: ["apocalipse", "ap", "apo"] },
];
