/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1SystemConnectionStatus200Holyrics } from './getApiV1SystemConnectionStatus200Holyrics';

export type GetApiV1SystemConnectionStatus200 = {
  holyrics: GetApiV1SystemConnectionStatus200Holyrics;
};
