/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1SchedulesCurrent200 = {
  id?: string;
  name?: string;
  type?: string;
  datetime?: string;
  lyrics_playlist?: {
  id?: string;
  song_id?: string;
  name?: string;
  type?: string;
  artist?: string;
  album?: string;
  key?: string;
  image?: string;
  video?: string;
  audio?: string;
  path?: string;
  active?: boolean;
  index?: number;
  [key: string]: unknown;
}[];
  media_playlist?: {
  id?: string;
  song_id?: string;
  name?: string;
  type?: string;
  artist?: string;
  album?: string;
  key?: string;
  image?: string;
  video?: string;
  audio?: string;
  path?: string;
  active?: boolean;
  index?: number;
  [key: string]: unknown;
}[];
  [key: string]: unknown;
}[] | {
  id?: string;
  name?: string;
  type?: string;
  datetime?: string;
  lyrics_playlist?: {
  id?: string;
  song_id?: string;
  name?: string;
  type?: string;
  artist?: string;
  album?: string;
  key?: string;
  image?: string;
  video?: string;
  audio?: string;
  path?: string;
  active?: boolean;
  index?: number;
  [key: string]: unknown;
}[];
  media_playlist?: {
  id?: string;
  song_id?: string;
  name?: string;
  type?: string;
  artist?: string;
  album?: string;
  key?: string;
  image?: string;
  video?: string;
  audio?: string;
  path?: string;
  active?: boolean;
  index?: number;
  [key: string]: unknown;
}[];
  [key: string]: unknown;
};
