/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1PlaylistsAddBodyType = typeof PostApiV1PlaylistsAddBodyType[keyof typeof PostApiV1PlaylistsAddBodyType];


export const PostApiV1PlaylistsAddBodyType = {
  song: 'song',
  media: 'media',
} as const;
