/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiV1AutomaticPresentationsPlayBody,
  PostApiV1AutomaticPresentationsPlayerActionBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get all automatic presentations
 */
export type getApiV1AutomaticPresentationsResponse200 = {
  data: void
  status: 200
}

export type getApiV1AutomaticPresentationsResponseSuccess = (getApiV1AutomaticPresentationsResponse200) & {
  headers: Headers;
};
;

export type getApiV1AutomaticPresentationsResponse = (getApiV1AutomaticPresentationsResponseSuccess)

export const getGetApiV1AutomaticPresentationsUrl = () => {




  return `/api/v1/automatic-presentations/`
}

export const getApiV1AutomaticPresentations = async ( options?: RequestInit): Promise<getApiV1AutomaticPresentationsResponse> => {

  return holyricsInstance<getApiV1AutomaticPresentationsResponse>(getGetApiV1AutomaticPresentationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AutomaticPresentationsQueryKey = () => {
    return [
    `/api/v1/automatic-presentations/`
    ] as const;
    }


export const getGetApiV1AutomaticPresentationsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AutomaticPresentationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>> = ({ signal }) => getApiV1AutomaticPresentations({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AutomaticPresentationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>>
export type GetApiV1AutomaticPresentationsQueryError = unknown


export function useGetApiV1AutomaticPresentations<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AutomaticPresentations<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AutomaticPresentations<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1AutomaticPresentations<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentations>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AutomaticPresentationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get automatic presentation by ID
 */
export type getApiV1AutomaticPresentationsIdResponse200 = {
  data: void
  status: 200
}

export type getApiV1AutomaticPresentationsIdResponseSuccess = (getApiV1AutomaticPresentationsIdResponse200) & {
  headers: Headers;
};
;

export type getApiV1AutomaticPresentationsIdResponse = (getApiV1AutomaticPresentationsIdResponseSuccess)

export const getGetApiV1AutomaticPresentationsIdUrl = (id: string,) => {




  return `/api/v1/automatic-presentations/${id}`
}

export const getApiV1AutomaticPresentationsId = async (id: string, options?: RequestInit): Promise<getApiV1AutomaticPresentationsIdResponse> => {

  return holyricsInstance<getApiV1AutomaticPresentationsIdResponse>(getGetApiV1AutomaticPresentationsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AutomaticPresentationsIdQueryKey = (id: string,) => {
    return [
    `/api/v1/automatic-presentations/${id}`
    ] as const;
    }


export const getGetApiV1AutomaticPresentationsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AutomaticPresentationsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>> = ({ signal }) => getApiV1AutomaticPresentationsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AutomaticPresentationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>>
export type GetApiV1AutomaticPresentationsIdQueryError = unknown


export function useGetApiV1AutomaticPresentationsId<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AutomaticPresentationsId<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AutomaticPresentationsId<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1AutomaticPresentationsId<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsId>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AutomaticPresentationsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Play automatic presentation
 */
export type postApiV1AutomaticPresentationsPlayResponse200 = {
  data: void
  status: 200
}

export type postApiV1AutomaticPresentationsPlayResponseSuccess = (postApiV1AutomaticPresentationsPlayResponse200) & {
  headers: Headers;
};
;

export type postApiV1AutomaticPresentationsPlayResponse = (postApiV1AutomaticPresentationsPlayResponseSuccess)

export const getPostApiV1AutomaticPresentationsPlayUrl = () => {




  return `/api/v1/automatic-presentations/play`
}

export const postApiV1AutomaticPresentationsPlay = async (postApiV1AutomaticPresentationsPlayBody: PostApiV1AutomaticPresentationsPlayBody, options?: RequestInit): Promise<postApiV1AutomaticPresentationsPlayResponse> => {

  return holyricsInstance<postApiV1AutomaticPresentationsPlayResponse>(getPostApiV1AutomaticPresentationsPlayUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1AutomaticPresentationsPlayBody,)
  }
);}




export const getPostApiV1AutomaticPresentationsPlayMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlay>>, TError,{data: PostApiV1AutomaticPresentationsPlayBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlay>>, TError,{data: PostApiV1AutomaticPresentationsPlayBody}, TContext> => {

const mutationKey = ['postApiV1AutomaticPresentationsPlay'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlay>>, {data: PostApiV1AutomaticPresentationsPlayBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AutomaticPresentationsPlay(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AutomaticPresentationsPlayMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlay>>>
    export type PostApiV1AutomaticPresentationsPlayMutationBody = PostApiV1AutomaticPresentationsPlayBody
    export type PostApiV1AutomaticPresentationsPlayMutationError = unknown

    export const usePostApiV1AutomaticPresentationsPlay = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlay>>, TError,{data: PostApiV1AutomaticPresentationsPlayBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlay>>,
        TError,
        {data: PostApiV1AutomaticPresentationsPlayBody},
        TContext
      > => {
      return useMutation(getPostApiV1AutomaticPresentationsPlayMutationOptions(options), queryClient);
    }
    /**
 * Get automatic presentation player info
 */
export type getApiV1AutomaticPresentationsPlayerInfoResponse200 = {
  data: void
  status: 200
}

export type getApiV1AutomaticPresentationsPlayerInfoResponseSuccess = (getApiV1AutomaticPresentationsPlayerInfoResponse200) & {
  headers: Headers;
};
;

export type getApiV1AutomaticPresentationsPlayerInfoResponse = (getApiV1AutomaticPresentationsPlayerInfoResponseSuccess)

export const getGetApiV1AutomaticPresentationsPlayerInfoUrl = () => {




  return `/api/v1/automatic-presentations/player-info`
}

export const getApiV1AutomaticPresentationsPlayerInfo = async ( options?: RequestInit): Promise<getApiV1AutomaticPresentationsPlayerInfoResponse> => {

  return holyricsInstance<getApiV1AutomaticPresentationsPlayerInfoResponse>(getGetApiV1AutomaticPresentationsPlayerInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AutomaticPresentationsPlayerInfoQueryKey = () => {
    return [
    `/api/v1/automatic-presentations/player-info`
    ] as const;
    }


export const getGetApiV1AutomaticPresentationsPlayerInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AutomaticPresentationsPlayerInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>> = ({ signal }) => getApiV1AutomaticPresentationsPlayerInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AutomaticPresentationsPlayerInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>>
export type GetApiV1AutomaticPresentationsPlayerInfoQueryError = unknown


export function useGetApiV1AutomaticPresentationsPlayerInfo<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AutomaticPresentationsPlayerInfo<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AutomaticPresentationsPlayerInfo<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1AutomaticPresentationsPlayerInfo<TData = Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AutomaticPresentationsPlayerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AutomaticPresentationsPlayerInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Perform automatic presentation player action
 */
export type postApiV1AutomaticPresentationsPlayerActionResponse200 = {
  data: void
  status: 200
}

export type postApiV1AutomaticPresentationsPlayerActionResponseSuccess = (postApiV1AutomaticPresentationsPlayerActionResponse200) & {
  headers: Headers;
};
;

export type postApiV1AutomaticPresentationsPlayerActionResponse = (postApiV1AutomaticPresentationsPlayerActionResponseSuccess)

export const getPostApiV1AutomaticPresentationsPlayerActionUrl = () => {




  return `/api/v1/automatic-presentations/player-action`
}

export const postApiV1AutomaticPresentationsPlayerAction = async (postApiV1AutomaticPresentationsPlayerActionBody: PostApiV1AutomaticPresentationsPlayerActionBody, options?: RequestInit): Promise<postApiV1AutomaticPresentationsPlayerActionResponse> => {

  return holyricsInstance<postApiV1AutomaticPresentationsPlayerActionResponse>(getPostApiV1AutomaticPresentationsPlayerActionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1AutomaticPresentationsPlayerActionBody,)
  }
);}




export const getPostApiV1AutomaticPresentationsPlayerActionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlayerAction>>, TError,{data: PostApiV1AutomaticPresentationsPlayerActionBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlayerAction>>, TError,{data: PostApiV1AutomaticPresentationsPlayerActionBody}, TContext> => {

const mutationKey = ['postApiV1AutomaticPresentationsPlayerAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlayerAction>>, {data: PostApiV1AutomaticPresentationsPlayerActionBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1AutomaticPresentationsPlayerAction(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1AutomaticPresentationsPlayerActionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlayerAction>>>
    export type PostApiV1AutomaticPresentationsPlayerActionMutationBody = PostApiV1AutomaticPresentationsPlayerActionBody
    export type PostApiV1AutomaticPresentationsPlayerActionMutationError = unknown

    export const usePostApiV1AutomaticPresentationsPlayerAction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlayerAction>>, TError,{data: PostApiV1AutomaticPresentationsPlayerActionBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1AutomaticPresentationsPlayerAction>>,
        TError,
        {data: PostApiV1AutomaticPresentationsPlayerActionBody},
        TContext
      > => {
      return useMutation(getPostApiV1AutomaticPresentationsPlayerActionMutationOptions(options), queryClient);
    }
