/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiV1QuizActionBody,
  PostApiV1QuizShowBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get quiz list
 */
export type getApiV1QuizResponse200 = {
  data: void
  status: 200
}

export type getApiV1QuizResponseSuccess = (getApiV1QuizResponse200) & {
  headers: Headers;
};
;

export type getApiV1QuizResponse = (getApiV1QuizResponseSuccess)

export const getGetApiV1QuizUrl = () => {




  return `/api/v1/quiz/`
}

export const getApiV1Quiz = async ( options?: RequestInit): Promise<getApiV1QuizResponse> => {

  return holyricsInstance<getApiV1QuizResponse>(getGetApiV1QuizUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1QuizQueryKey = () => {
    return [
    `/api/v1/quiz/`
    ] as const;
    }


export const getGetApiV1QuizQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Quiz>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quiz>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1QuizQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Quiz>>> = ({ signal }) => getApiV1Quiz({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quiz>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1QuizQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Quiz>>>
export type GetApiV1QuizQueryError = unknown


export function useGetApiV1Quiz<TData = Awaited<ReturnType<typeof getApiV1Quiz>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quiz>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Quiz>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Quiz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Quiz<TData = Awaited<ReturnType<typeof getApiV1Quiz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quiz>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Quiz>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Quiz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Quiz<TData = Awaited<ReturnType<typeof getApiV1Quiz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quiz>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1Quiz<TData = Awaited<ReturnType<typeof getApiV1Quiz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Quiz>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1QuizQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Show quiz
 */
export type postApiV1QuizShowResponse200 = {
  data: void
  status: 200
}

export type postApiV1QuizShowResponseSuccess = (postApiV1QuizShowResponse200) & {
  headers: Headers;
};
;

export type postApiV1QuizShowResponse = (postApiV1QuizShowResponseSuccess)

export const getPostApiV1QuizShowUrl = () => {




  return `/api/v1/quiz/show`
}

export const postApiV1QuizShow = async (postApiV1QuizShowBody: PostApiV1QuizShowBody, options?: RequestInit): Promise<postApiV1QuizShowResponse> => {

  return holyricsInstance<postApiV1QuizShowResponse>(getPostApiV1QuizShowUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1QuizShowBody,)
  }
);}




export const getPostApiV1QuizShowMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizShow>>, TError,{data: PostApiV1QuizShowBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizShow>>, TError,{data: PostApiV1QuizShowBody}, TContext> => {

const mutationKey = ['postApiV1QuizShow'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuizShow>>, {data: PostApiV1QuizShowBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1QuizShow(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuizShowMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuizShow>>>
    export type PostApiV1QuizShowMutationBody = PostApiV1QuizShowBody
    export type PostApiV1QuizShowMutationError = unknown

    export const usePostApiV1QuizShow = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizShow>>, TError,{data: PostApiV1QuizShowBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuizShow>>,
        TError,
        {data: PostApiV1QuizShowBody},
        TContext
      > => {
      return useMutation(getPostApiV1QuizShowMutationOptions(options), queryClient);
    }
    /**
 * Perform quiz action
 */
export type postApiV1QuizActionResponse200 = {
  data: void
  status: 200
}

export type postApiV1QuizActionResponseSuccess = (postApiV1QuizActionResponse200) & {
  headers: Headers;
};
;

export type postApiV1QuizActionResponse = (postApiV1QuizActionResponseSuccess)

export const getPostApiV1QuizActionUrl = () => {




  return `/api/v1/quiz/action`
}

export const postApiV1QuizAction = async (postApiV1QuizActionBody: PostApiV1QuizActionBody, options?: RequestInit): Promise<postApiV1QuizActionResponse> => {

  return holyricsInstance<postApiV1QuizActionResponse>(getPostApiV1QuizActionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1QuizActionBody,)
  }
);}




export const getPostApiV1QuizActionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizAction>>, TError,{data: PostApiV1QuizActionBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizAction>>, TError,{data: PostApiV1QuizActionBody}, TContext> => {

const mutationKey = ['postApiV1QuizAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuizAction>>, {data: PostApiV1QuizActionBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1QuizAction(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuizActionMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuizAction>>>
    export type PostApiV1QuizActionMutationBody = PostApiV1QuizActionBody
    export type PostApiV1QuizActionMutationError = unknown

    export const usePostApiV1QuizAction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuizAction>>, TError,{data: PostApiV1QuizActionBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuizAction>>,
        TError,
        {data: PostApiV1QuizActionBody},
        TContext
      > => {
      return useMutation(getPostApiV1QuizActionMutationOptions(options), queryClient);
    }
