/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1AuthLoginTokenParams
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Login with a new token
 */
export type getApiV1AuthLoginTokenResponse200 = {
  data: void
  status: 200
}

export type getApiV1AuthLoginTokenResponseSuccess = (getApiV1AuthLoginTokenResponse200) & {
  headers: Headers;
};
;

export type getApiV1AuthLoginTokenResponse = (getApiV1AuthLoginTokenResponseSuccess)

export const getGetApiV1AuthLoginTokenUrl = (params: GetApiV1AuthLoginTokenParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/auth/login/token?${stringifiedParams}` : `/api/v1/auth/login/token`
}

export const getApiV1AuthLoginToken = async (params: GetApiV1AuthLoginTokenParams, options?: RequestInit): Promise<getApiV1AuthLoginTokenResponse> => {

  return holyricsInstance<getApiV1AuthLoginTokenResponse>(getGetApiV1AuthLoginTokenUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AuthLoginTokenQueryKey = (params?: GetApiV1AuthLoginTokenParams,) => {
    return [
    `/api/v1/auth/login/token`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1AuthLoginTokenQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError = unknown>(params: GetApiV1AuthLoginTokenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AuthLoginTokenQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthLoginToken>>> = ({ signal }) => getApiV1AuthLoginToken(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AuthLoginTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AuthLoginToken>>>
export type GetApiV1AuthLoginTokenQueryError = unknown


export function useGetApiV1AuthLoginToken<TData = Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError = unknown>(
 params: GetApiV1AuthLoginTokenParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthLoginToken>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthLoginToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthLoginToken<TData = Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError = unknown>(
 params: GetApiV1AuthLoginTokenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthLoginToken>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthLoginToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthLoginToken<TData = Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError = unknown>(
 params: GetApiV1AuthLoginTokenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1AuthLoginToken<TData = Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError = unknown>(
 params: GetApiV1AuthLoginTokenParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginToken>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AuthLoginTokenQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Login/Re-authenticate using the stored token (from cookies or environment)
 */
export type getApiV1AuthLoginHashResponse200 = {
  data: void
  status: 200
}

export type getApiV1AuthLoginHashResponseSuccess = (getApiV1AuthLoginHashResponse200) & {
  headers: Headers;
};
;

export type getApiV1AuthLoginHashResponse = (getApiV1AuthLoginHashResponseSuccess)

export const getGetApiV1AuthLoginHashUrl = () => {




  return `/api/v1/auth/login/hash`
}

export const getApiV1AuthLoginHash = async ( options?: RequestInit): Promise<getApiV1AuthLoginHashResponse> => {

  return holyricsInstance<getApiV1AuthLoginHashResponse>(getGetApiV1AuthLoginHashUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1AuthLoginHashQueryKey = () => {
    return [
    `/api/v1/auth/login/hash`
    ] as const;
    }


export const getGetApiV1AuthLoginHashQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1AuthLoginHashQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuthLoginHash>>> = ({ signal }) => getApiV1AuthLoginHash({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1AuthLoginHashQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1AuthLoginHash>>>
export type GetApiV1AuthLoginHashQueryError = unknown


export function useGetApiV1AuthLoginHash<TData = Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthLoginHash>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthLoginHash>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthLoginHash<TData = Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1AuthLoginHash>>,
          TError,
          Awaited<ReturnType<typeof getApiV1AuthLoginHash>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1AuthLoginHash<TData = Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1AuthLoginHash<TData = Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1AuthLoginHash>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1AuthLoginHashQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






