/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1SongsIdParams,
  GetApiV1SongsParams,
  PostApiV1SongsRealTimeKeyBody,
  PostApiV1SongsSearchBody,
  PostApiV1SongsShowBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get all songs
 */
export type getApiV1SongsResponse200 = {
  data: void
  status: 200
}

export type getApiV1SongsResponseSuccess = (getApiV1SongsResponse200) & {
  headers: Headers;
};
;

export type getApiV1SongsResponse = (getApiV1SongsResponseSuccess)

export const getGetApiV1SongsUrl = (params?: GetApiV1SongsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/songs/?${stringifiedParams}` : `/api/v1/songs/`
}

export const getApiV1Songs = async (params?: GetApiV1SongsParams, options?: RequestInit): Promise<getApiV1SongsResponse> => {

  return holyricsInstance<getApiV1SongsResponse>(getGetApiV1SongsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SongsQueryKey = (params?: GetApiV1SongsParams,) => {
    return [
    `/api/v1/songs/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1SongsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Songs>>, TError = unknown>(params?: GetApiV1SongsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Songs>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SongsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Songs>>> = ({ signal }) => getApiV1Songs(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Songs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SongsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Songs>>>
export type GetApiV1SongsQueryError = unknown


export function useGetApiV1Songs<TData = Awaited<ReturnType<typeof getApiV1Songs>>, TError = unknown>(
 params: undefined |  GetApiV1SongsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Songs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Songs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Songs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Songs<TData = Awaited<ReturnType<typeof getApiV1Songs>>, TError = unknown>(
 params?: GetApiV1SongsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Songs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Songs>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Songs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Songs<TData = Awaited<ReturnType<typeof getApiV1Songs>>, TError = unknown>(
 params?: GetApiV1SongsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Songs>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1Songs<TData = Awaited<ReturnType<typeof getApiV1Songs>>, TError = unknown>(
 params?: GetApiV1SongsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Songs>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SongsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get song by ID
 */
export type getApiV1SongsIdResponse200 = {
  data: void
  status: 200
}

export type getApiV1SongsIdResponseSuccess = (getApiV1SongsIdResponse200) & {
  headers: Headers;
};
;

export type getApiV1SongsIdResponse = (getApiV1SongsIdResponseSuccess)

export const getGetApiV1SongsIdUrl = (id: string,
    params?: GetApiV1SongsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/songs/${id}?${stringifiedParams}` : `/api/v1/songs/${id}`
}

export const getApiV1SongsId = async (id: string,
    params?: GetApiV1SongsIdParams, options?: RequestInit): Promise<getApiV1SongsIdResponse> => {

  return holyricsInstance<getApiV1SongsIdResponse>(getGetApiV1SongsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SongsIdQueryKey = (id: string,
    params?: GetApiV1SongsIdParams,) => {
    return [
    `/api/v1/songs/${id}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1SongsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SongsId>>, TError = unknown>(id: string,
    params?: GetApiV1SongsIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsId>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SongsIdQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SongsId>>> = ({ signal }) => getApiV1SongsId(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SongsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SongsId>>>
export type GetApiV1SongsIdQueryError = unknown


export function useGetApiV1SongsId<TData = Awaited<ReturnType<typeof getApiV1SongsId>>, TError = unknown>(
 id: string,
    params: undefined |  GetApiV1SongsIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SongsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SongsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SongsId<TData = Awaited<ReturnType<typeof getApiV1SongsId>>, TError = unknown>(
 id: string,
    params?: GetApiV1SongsIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SongsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SongsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SongsId<TData = Awaited<ReturnType<typeof getApiV1SongsId>>, TError = unknown>(
 id: string,
    params?: GetApiV1SongsIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsId>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SongsId<TData = Awaited<ReturnType<typeof getApiV1SongsId>>, TError = unknown>(
 id: string,
    params?: GetApiV1SongsIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsId>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SongsIdQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Search songs
 */
export type postApiV1SongsSearchResponse200 = {
  data: void
  status: 200
}

export type postApiV1SongsSearchResponseSuccess = (postApiV1SongsSearchResponse200) & {
  headers: Headers;
};
;

export type postApiV1SongsSearchResponse = (postApiV1SongsSearchResponseSuccess)

export const getPostApiV1SongsSearchUrl = () => {




  return `/api/v1/songs/search`
}

export const postApiV1SongsSearch = async (postApiV1SongsSearchBody: PostApiV1SongsSearchBody, options?: RequestInit): Promise<postApiV1SongsSearchResponse> => {

  return holyricsInstance<postApiV1SongsSearchResponse>(getPostApiV1SongsSearchUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SongsSearchBody,)
  }
);}




export const getPostApiV1SongsSearchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsSearch>>, TError,{data: PostApiV1SongsSearchBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsSearch>>, TError,{data: PostApiV1SongsSearchBody}, TContext> => {

const mutationKey = ['postApiV1SongsSearch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SongsSearch>>, {data: PostApiV1SongsSearchBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SongsSearch(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SongsSearchMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SongsSearch>>>
    export type PostApiV1SongsSearchMutationBody = PostApiV1SongsSearchBody
    export type PostApiV1SongsSearchMutationError = unknown

    export const usePostApiV1SongsSearch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsSearch>>, TError,{data: PostApiV1SongsSearchBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SongsSearch>>,
        TError,
        {data: PostApiV1SongsSearchBody},
        TContext
      > => {
      return useMutation(getPostApiV1SongsSearchMutationOptions(options), queryClient);
    }
    /**
 * Show song on screen
 */
export type postApiV1SongsShowResponse200 = {
  data: void
  status: 200
}

export type postApiV1SongsShowResponseSuccess = (postApiV1SongsShowResponse200) & {
  headers: Headers;
};
;

export type postApiV1SongsShowResponse = (postApiV1SongsShowResponseSuccess)

export const getPostApiV1SongsShowUrl = () => {




  return `/api/v1/songs/show`
}

export const postApiV1SongsShow = async (postApiV1SongsShowBody: PostApiV1SongsShowBody, options?: RequestInit): Promise<postApiV1SongsShowResponse> => {

  return holyricsInstance<postApiV1SongsShowResponse>(getPostApiV1SongsShowUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SongsShowBody,)
  }
);}




export const getPostApiV1SongsShowMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsShow>>, TError,{data: PostApiV1SongsShowBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsShow>>, TError,{data: PostApiV1SongsShowBody}, TContext> => {

const mutationKey = ['postApiV1SongsShow'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SongsShow>>, {data: PostApiV1SongsShowBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SongsShow(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SongsShowMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SongsShow>>>
    export type PostApiV1SongsShowMutationBody = PostApiV1SongsShowBody
    export type PostApiV1SongsShowMutationError = unknown

    export const usePostApiV1SongsShow = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsShow>>, TError,{data: PostApiV1SongsShowBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SongsShow>>,
        TError,
        {data: PostApiV1SongsShowBody},
        TContext
      > => {
      return useMutation(getPostApiV1SongsShowMutationOptions(options), queryClient);
    }
    /**
 * Get real-time song key
 */
export type getApiV1SongsRealTimeKeyResponse200 = {
  data: void
  status: 200
}

export type getApiV1SongsRealTimeKeyResponseSuccess = (getApiV1SongsRealTimeKeyResponse200) & {
  headers: Headers;
};
;

export type getApiV1SongsRealTimeKeyResponse = (getApiV1SongsRealTimeKeyResponseSuccess)

export const getGetApiV1SongsRealTimeKeyUrl = () => {




  return `/api/v1/songs/real-time-key`
}

export const getApiV1SongsRealTimeKey = async ( options?: RequestInit): Promise<getApiV1SongsRealTimeKeyResponse> => {

  return holyricsInstance<getApiV1SongsRealTimeKeyResponse>(getGetApiV1SongsRealTimeKeyUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SongsRealTimeKeyQueryKey = () => {
    return [
    `/api/v1/songs/real-time-key`
    ] as const;
    }


export const getGetApiV1SongsRealTimeKeyQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SongsRealTimeKeyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>> = ({ signal }) => getApiV1SongsRealTimeKey({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SongsRealTimeKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>>
export type GetApiV1SongsRealTimeKeyQueryError = unknown


export function useGetApiV1SongsRealTimeKey<TData = Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SongsRealTimeKey<TData = Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SongsRealTimeKey<TData = Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SongsRealTimeKey<TData = Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SongsRealTimeKey>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SongsRealTimeKeyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set real-time song key
 */
export type postApiV1SongsRealTimeKeyResponse200 = {
  data: void
  status: 200
}

export type postApiV1SongsRealTimeKeyResponseSuccess = (postApiV1SongsRealTimeKeyResponse200) & {
  headers: Headers;
};
;

export type postApiV1SongsRealTimeKeyResponse = (postApiV1SongsRealTimeKeyResponseSuccess)

export const getPostApiV1SongsRealTimeKeyUrl = () => {




  return `/api/v1/songs/real-time-key`
}

export const postApiV1SongsRealTimeKey = async (postApiV1SongsRealTimeKeyBody: PostApiV1SongsRealTimeKeyBody, options?: RequestInit): Promise<postApiV1SongsRealTimeKeyResponse> => {

  return holyricsInstance<postApiV1SongsRealTimeKeyResponse>(getPostApiV1SongsRealTimeKeyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SongsRealTimeKeyBody,)
  }
);}




export const getPostApiV1SongsRealTimeKeyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsRealTimeKey>>, TError,{data: PostApiV1SongsRealTimeKeyBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsRealTimeKey>>, TError,{data: PostApiV1SongsRealTimeKeyBody}, TContext> => {

const mutationKey = ['postApiV1SongsRealTimeKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SongsRealTimeKey>>, {data: PostApiV1SongsRealTimeKeyBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SongsRealTimeKey(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SongsRealTimeKeyMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SongsRealTimeKey>>>
    export type PostApiV1SongsRealTimeKeyMutationBody = PostApiV1SongsRealTimeKeyBody
    export type PostApiV1SongsRealTimeKeyMutationError = unknown

    export const usePostApiV1SongsRealTimeKey = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SongsRealTimeKey>>, TError,{data: PostApiV1SongsRealTimeKeyBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SongsRealTimeKey>>,
        TError,
        {data: PostApiV1SongsRealTimeKeyBody},
        TContext
      > => {
      return useMutation(getPostApiV1SongsRealTimeKeyMutationOptions(options), queryClient);
    }
