/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1BackgroundsThumbnailParams,
  PostApiV1BackgroundsBpmBody,
  PostApiV1BackgroundsHueBody,
  PostApiV1BackgroundsSetBody,
  PostApiV1BackgroundsSetLogoBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get current background info
 */
export type getApiV1BackgroundsCurrentResponse200 = {
  data: void
  status: 200
}

export type getApiV1BackgroundsCurrentResponseSuccess = (getApiV1BackgroundsCurrentResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsCurrentResponse = (getApiV1BackgroundsCurrentResponseSuccess)

export const getGetApiV1BackgroundsCurrentUrl = () => {




  return `/api/v1/backgrounds/current`
}

export const getApiV1BackgroundsCurrent = async ( options?: RequestInit): Promise<getApiV1BackgroundsCurrentResponse> => {

  return holyricsInstance<getApiV1BackgroundsCurrentResponse>(getGetApiV1BackgroundsCurrentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsCurrentQueryKey = () => {
    return [
    `/api/v1/backgrounds/current`
    ] as const;
    }


export const getGetApiV1BackgroundsCurrentQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsCurrentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>> = ({ signal }) => getApiV1BackgroundsCurrent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>>
export type GetApiV1BackgroundsCurrentQueryError = unknown


export function useGetApiV1BackgroundsCurrent<TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsCurrent<TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsCurrent<TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BackgroundsCurrent<TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get current theme info
 */
export type getApiV1BackgroundsCurrentThemeResponse200 = {
  data: unknown | null
  status: 200
}

export type getApiV1BackgroundsCurrentThemeResponseSuccess = (getApiV1BackgroundsCurrentThemeResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsCurrentThemeResponse = (getApiV1BackgroundsCurrentThemeResponseSuccess)

export const getGetApiV1BackgroundsCurrentThemeUrl = () => {




  return `/api/v1/backgrounds/current-theme`
}

export const getApiV1BackgroundsCurrentTheme = async ( options?: RequestInit): Promise<getApiV1BackgroundsCurrentThemeResponse> => {

  return holyricsInstance<getApiV1BackgroundsCurrentThemeResponse>(getGetApiV1BackgroundsCurrentThemeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsCurrentThemeQueryKey = () => {
    return [
    `/api/v1/backgrounds/current-theme`
    ] as const;
    }


export const getGetApiV1BackgroundsCurrentThemeQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsCurrentThemeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>> = ({ signal }) => getApiV1BackgroundsCurrentTheme({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsCurrentThemeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>>
export type GetApiV1BackgroundsCurrentThemeQueryError = unknown


export function useGetApiV1BackgroundsCurrentTheme<TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsCurrentTheme<TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsCurrentTheme<TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BackgroundsCurrentTheme<TData = Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsCurrentTheme>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsCurrentThemeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get all themes
 */
export type getApiV1BackgroundsThemesResponse200 = {
  data: unknown[]
  status: 200
}

export type getApiV1BackgroundsThemesResponseSuccess = (getApiV1BackgroundsThemesResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsThemesResponse = (getApiV1BackgroundsThemesResponseSuccess)

export const getGetApiV1BackgroundsThemesUrl = () => {




  return `/api/v1/backgrounds/themes`
}

export const getApiV1BackgroundsThemes = async ( options?: RequestInit): Promise<getApiV1BackgroundsThemesResponse> => {

  return holyricsInstance<getApiV1BackgroundsThemesResponse>(getGetApiV1BackgroundsThemesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsThemesQueryKey = () => {
    return [
    `/api/v1/backgrounds/themes`
    ] as const;
    }


export const getGetApiV1BackgroundsThemesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsThemesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>> = ({ signal }) => getApiV1BackgroundsThemes({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsThemesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>>
export type GetApiV1BackgroundsThemesQueryError = unknown


export function useGetApiV1BackgroundsThemes<TData = Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsThemes<TData = Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsThemes<TData = Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BackgroundsThemes<TData = Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThemes>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsThemesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get all backgrounds
 */
export type getApiV1BackgroundsResponse200 = {
  data: void
  status: 200
}

export type getApiV1BackgroundsResponseSuccess = (getApiV1BackgroundsResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsResponse = (getApiV1BackgroundsResponseSuccess)

export const getGetApiV1BackgroundsUrl = () => {




  return `/api/v1/backgrounds/`
}

export const getApiV1Backgrounds = async ( options?: RequestInit): Promise<getApiV1BackgroundsResponse> => {

  return holyricsInstance<getApiV1BackgroundsResponse>(getGetApiV1BackgroundsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsQueryKey = () => {
    return [
    `/api/v1/backgrounds/`
    ] as const;
    }


export const getGetApiV1BackgroundsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Backgrounds>>> = ({ signal }) => getApiV1Backgrounds({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Backgrounds>>>
export type GetApiV1BackgroundsQueryError = unknown


export function useGetApiV1Backgrounds<TData = Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Backgrounds>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Backgrounds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Backgrounds<TData = Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Backgrounds>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Backgrounds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Backgrounds<TData = Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1Backgrounds<TData = Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Backgrounds>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get background tags
 */
export type getApiV1BackgroundsTagsResponse200 = {
  data: void
  status: 200
}

export type getApiV1BackgroundsTagsResponseSuccess = (getApiV1BackgroundsTagsResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsTagsResponse = (getApiV1BackgroundsTagsResponseSuccess)

export const getGetApiV1BackgroundsTagsUrl = () => {




  return `/api/v1/backgrounds/tags`
}

export const getApiV1BackgroundsTags = async ( options?: RequestInit): Promise<getApiV1BackgroundsTagsResponse> => {

  return holyricsInstance<getApiV1BackgroundsTagsResponse>(getGetApiV1BackgroundsTagsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsTagsQueryKey = () => {
    return [
    `/api/v1/backgrounds/tags`
    ] as const;
    }


export const getGetApiV1BackgroundsTagsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsTagsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BackgroundsTags>>> = ({ signal }) => getApiV1BackgroundsTags({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsTagsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BackgroundsTags>>>
export type GetApiV1BackgroundsTagsQueryError = unknown


export function useGetApiV1BackgroundsTags<TData = Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsTags>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsTags>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsTags<TData = Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsTags>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsTags>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsTags<TData = Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BackgroundsTags<TData = Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsTags>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsTagsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set current background
 */
export type postApiV1BackgroundsSetResponse200 = {
  data: void
  status: 200
}

export type postApiV1BackgroundsSetResponseSuccess = (postApiV1BackgroundsSetResponse200) & {
  headers: Headers;
};
;

export type postApiV1BackgroundsSetResponse = (postApiV1BackgroundsSetResponseSuccess)

export const getPostApiV1BackgroundsSetUrl = () => {




  return `/api/v1/backgrounds/set`
}

export const postApiV1BackgroundsSet = async (postApiV1BackgroundsSetBody: PostApiV1BackgroundsSetBody, options?: RequestInit): Promise<postApiV1BackgroundsSetResponse> => {

  return holyricsInstance<postApiV1BackgroundsSetResponse>(getPostApiV1BackgroundsSetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1BackgroundsSetBody,)
  }
);}




export const getPostApiV1BackgroundsSetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsSet>>, TError,{data: PostApiV1BackgroundsSetBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsSet>>, TError,{data: PostApiV1BackgroundsSetBody}, TContext> => {

const mutationKey = ['postApiV1BackgroundsSet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BackgroundsSet>>, {data: PostApiV1BackgroundsSetBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BackgroundsSet(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BackgroundsSetMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BackgroundsSet>>>
    export type PostApiV1BackgroundsSetMutationBody = PostApiV1BackgroundsSetBody
    export type PostApiV1BackgroundsSetMutationError = unknown

    export const usePostApiV1BackgroundsSet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsSet>>, TError,{data: PostApiV1BackgroundsSetBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BackgroundsSet>>,
        TError,
        {data: PostApiV1BackgroundsSetBody},
        TContext
      > => {
      return useMutation(getPostApiV1BackgroundsSetMutationOptions(options), queryClient);
    }
    /**
 * Get thumbnail for item
 */
export type getApiV1BackgroundsThumbnailResponse200 = {
  data: void
  status: 200
}

export type getApiV1BackgroundsThumbnailResponseSuccess = (getApiV1BackgroundsThumbnailResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsThumbnailResponse = (getApiV1BackgroundsThumbnailResponseSuccess)

export const getGetApiV1BackgroundsThumbnailUrl = (params: GetApiV1BackgroundsThumbnailParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/backgrounds/thumbnail?${stringifiedParams}` : `/api/v1/backgrounds/thumbnail`
}

export const getApiV1BackgroundsThumbnail = async (params: GetApiV1BackgroundsThumbnailParams, options?: RequestInit): Promise<getApiV1BackgroundsThumbnailResponse> => {

  return holyricsInstance<getApiV1BackgroundsThumbnailResponse>(getGetApiV1BackgroundsThumbnailUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsThumbnailQueryKey = (params?: GetApiV1BackgroundsThumbnailParams,) => {
    return [
    `/api/v1/backgrounds/thumbnail`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV1BackgroundsThumbnailQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError = unknown>(params: GetApiV1BackgroundsThumbnailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsThumbnailQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>> = ({ signal }) => getApiV1BackgroundsThumbnail(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsThumbnailQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>>
export type GetApiV1BackgroundsThumbnailQueryError = unknown


export function useGetApiV1BackgroundsThumbnail<TData = Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError = unknown>(
 params: GetApiV1BackgroundsThumbnailParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsThumbnail<TData = Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError = unknown>(
 params: GetApiV1BackgroundsThumbnailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsThumbnail<TData = Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError = unknown>(
 params: GetApiV1BackgroundsThumbnailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BackgroundsThumbnail<TData = Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError = unknown>(
 params: GetApiV1BackgroundsThumbnailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsThumbnail>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsThumbnailQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get color map
 */
export type getApiV1BackgroundsColorMapResponse200 = {
  data: void
  status: 200
}

export type getApiV1BackgroundsColorMapResponseSuccess = (getApiV1BackgroundsColorMapResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsColorMapResponse = (getApiV1BackgroundsColorMapResponseSuccess)

export const getGetApiV1BackgroundsColorMapUrl = () => {




  return `/api/v1/backgrounds/color-map`
}

export const getApiV1BackgroundsColorMap = async ( options?: RequestInit): Promise<getApiV1BackgroundsColorMapResponse> => {

  return holyricsInstance<getApiV1BackgroundsColorMapResponse>(getGetApiV1BackgroundsColorMapUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsColorMapQueryKey = () => {
    return [
    `/api/v1/backgrounds/color-map`
    ] as const;
    }


export const getGetApiV1BackgroundsColorMapQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsColorMapQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>> = ({ signal }) => getApiV1BackgroundsColorMap({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsColorMapQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>>
export type GetApiV1BackgroundsColorMapQueryError = unknown


export function useGetApiV1BackgroundsColorMap<TData = Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsColorMap<TData = Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsColorMap<TData = Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BackgroundsColorMap<TData = Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsColorMap>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsColorMapQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set logo background
 */
export type postApiV1BackgroundsSetLogoResponse200 = {
  data: void
  status: 200
}

export type postApiV1BackgroundsSetLogoResponseSuccess = (postApiV1BackgroundsSetLogoResponse200) & {
  headers: Headers;
};
;

export type postApiV1BackgroundsSetLogoResponse = (postApiV1BackgroundsSetLogoResponseSuccess)

export const getPostApiV1BackgroundsSetLogoUrl = () => {




  return `/api/v1/backgrounds/set-logo`
}

export const postApiV1BackgroundsSetLogo = async (postApiV1BackgroundsSetLogoBody: PostApiV1BackgroundsSetLogoBody, options?: RequestInit): Promise<postApiV1BackgroundsSetLogoResponse> => {

  return holyricsInstance<postApiV1BackgroundsSetLogoResponse>(getPostApiV1BackgroundsSetLogoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1BackgroundsSetLogoBody,)
  }
);}




export const getPostApiV1BackgroundsSetLogoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsSetLogo>>, TError,{data: PostApiV1BackgroundsSetLogoBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsSetLogo>>, TError,{data: PostApiV1BackgroundsSetLogoBody}, TContext> => {

const mutationKey = ['postApiV1BackgroundsSetLogo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BackgroundsSetLogo>>, {data: PostApiV1BackgroundsSetLogoBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BackgroundsSetLogo(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BackgroundsSetLogoMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BackgroundsSetLogo>>>
    export type PostApiV1BackgroundsSetLogoMutationBody = PostApiV1BackgroundsSetLogoBody
    export type PostApiV1BackgroundsSetLogoMutationError = unknown

    export const usePostApiV1BackgroundsSetLogo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsSetLogo>>, TError,{data: PostApiV1BackgroundsSetLogoBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BackgroundsSetLogo>>,
        TError,
        {data: PostApiV1BackgroundsSetLogoBody},
        TContext
      > => {
      return useMutation(getPostApiV1BackgroundsSetLogoMutationOptions(options), queryClient);
    }
    /**
 * Get current BPM
 */
export type getApiV1BackgroundsBpmResponse200 = {
  data: void
  status: 200
}

export type getApiV1BackgroundsBpmResponseSuccess = (getApiV1BackgroundsBpmResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsBpmResponse = (getApiV1BackgroundsBpmResponseSuccess)

export const getGetApiV1BackgroundsBpmUrl = () => {




  return `/api/v1/backgrounds/bpm`
}

export const getApiV1BackgroundsBpm = async ( options?: RequestInit): Promise<getApiV1BackgroundsBpmResponse> => {

  return holyricsInstance<getApiV1BackgroundsBpmResponse>(getGetApiV1BackgroundsBpmUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsBpmQueryKey = () => {
    return [
    `/api/v1/backgrounds/bpm`
    ] as const;
    }


export const getGetApiV1BackgroundsBpmQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsBpmQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>> = ({ signal }) => getApiV1BackgroundsBpm({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsBpmQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>>
export type GetApiV1BackgroundsBpmQueryError = unknown


export function useGetApiV1BackgroundsBpm<TData = Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsBpm<TData = Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsBpm<TData = Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BackgroundsBpm<TData = Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsBpm>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsBpmQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set current BPM
 */
export type postApiV1BackgroundsBpmResponse200 = {
  data: void
  status: 200
}

export type postApiV1BackgroundsBpmResponseSuccess = (postApiV1BackgroundsBpmResponse200) & {
  headers: Headers;
};
;

export type postApiV1BackgroundsBpmResponse = (postApiV1BackgroundsBpmResponseSuccess)

export const getPostApiV1BackgroundsBpmUrl = () => {




  return `/api/v1/backgrounds/bpm`
}

export const postApiV1BackgroundsBpm = async (postApiV1BackgroundsBpmBody: PostApiV1BackgroundsBpmBody, options?: RequestInit): Promise<postApiV1BackgroundsBpmResponse> => {

  return holyricsInstance<postApiV1BackgroundsBpmResponse>(getPostApiV1BackgroundsBpmUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1BackgroundsBpmBody,)
  }
);}




export const getPostApiV1BackgroundsBpmMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsBpm>>, TError,{data: PostApiV1BackgroundsBpmBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsBpm>>, TError,{data: PostApiV1BackgroundsBpmBody}, TContext> => {

const mutationKey = ['postApiV1BackgroundsBpm'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BackgroundsBpm>>, {data: PostApiV1BackgroundsBpmBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BackgroundsBpm(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BackgroundsBpmMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BackgroundsBpm>>>
    export type PostApiV1BackgroundsBpmMutationBody = PostApiV1BackgroundsBpmBody
    export type PostApiV1BackgroundsBpmMutationError = unknown

    export const usePostApiV1BackgroundsBpm = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsBpm>>, TError,{data: PostApiV1BackgroundsBpmBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BackgroundsBpm>>,
        TError,
        {data: PostApiV1BackgroundsBpmBody},
        TContext
      > => {
      return useMutation(getPostApiV1BackgroundsBpmMutationOptions(options), queryClient);
    }
    /**
 * Get current Hue
 */
export type getApiV1BackgroundsHueResponse200 = {
  data: void
  status: 200
}

export type getApiV1BackgroundsHueResponseSuccess = (getApiV1BackgroundsHueResponse200) & {
  headers: Headers;
};
;

export type getApiV1BackgroundsHueResponse = (getApiV1BackgroundsHueResponseSuccess)

export const getGetApiV1BackgroundsHueUrl = () => {




  return `/api/v1/backgrounds/hue`
}

export const getApiV1BackgroundsHue = async ( options?: RequestInit): Promise<getApiV1BackgroundsHueResponse> => {

  return holyricsInstance<getApiV1BackgroundsHueResponse>(getGetApiV1BackgroundsHueUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1BackgroundsHueQueryKey = () => {
    return [
    `/api/v1/backgrounds/hue`
    ] as const;
    }


export const getGetApiV1BackgroundsHueQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1BackgroundsHueQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1BackgroundsHue>>> = ({ signal }) => getApiV1BackgroundsHue({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1BackgroundsHueQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1BackgroundsHue>>>
export type GetApiV1BackgroundsHueQueryError = unknown


export function useGetApiV1BackgroundsHue<TData = Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsHue>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsHue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsHue<TData = Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1BackgroundsHue>>,
          TError,
          Awaited<ReturnType<typeof getApiV1BackgroundsHue>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1BackgroundsHue<TData = Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1BackgroundsHue<TData = Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1BackgroundsHue>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1BackgroundsHueQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set current Hue
 */
export type postApiV1BackgroundsHueResponse200 = {
  data: void
  status: 200
}

export type postApiV1BackgroundsHueResponseSuccess = (postApiV1BackgroundsHueResponse200) & {
  headers: Headers;
};
;

export type postApiV1BackgroundsHueResponse = (postApiV1BackgroundsHueResponseSuccess)

export const getPostApiV1BackgroundsHueUrl = () => {




  return `/api/v1/backgrounds/hue`
}

export const postApiV1BackgroundsHue = async (postApiV1BackgroundsHueBody: PostApiV1BackgroundsHueBody, options?: RequestInit): Promise<postApiV1BackgroundsHueResponse> => {

  return holyricsInstance<postApiV1BackgroundsHueResponse>(getPostApiV1BackgroundsHueUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1BackgroundsHueBody,)
  }
);}




export const getPostApiV1BackgroundsHueMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsHue>>, TError,{data: PostApiV1BackgroundsHueBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsHue>>, TError,{data: PostApiV1BackgroundsHueBody}, TContext> => {

const mutationKey = ['postApiV1BackgroundsHue'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1BackgroundsHue>>, {data: PostApiV1BackgroundsHueBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1BackgroundsHue(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1BackgroundsHueMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1BackgroundsHue>>>
    export type PostApiV1BackgroundsHueMutationBody = PostApiV1BackgroundsHueBody
    export type PostApiV1BackgroundsHueMutationError = unknown

    export const usePostApiV1BackgroundsHue = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1BackgroundsHue>>, TError,{data: PostApiV1BackgroundsHueBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1BackgroundsHue>>,
        TError,
        {data: PostApiV1BackgroundsHueBody},
        TContext
      > => {
      return useMutation(getPostApiV1BackgroundsHueMutationOptions(options), queryClient);
    }
