/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';


export const getGetApiV1BackgroundsCurrentThemeResponseMock = (): unknown | null => ({})


export const getGetApiV1BackgroundsCurrentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/current', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1BackgroundsCurrentThemeMockHandler = (overrideResponse?: unknown | null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown | null> | unknown | null), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/current-theme', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1BackgroundsCurrentThemeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiV1BackgroundsThemesMockHandler = (overrideResponse?: unknown[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown[]> | unknown[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/themes', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1BackgroundsMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1BackgroundsTagsMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/tags', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1BackgroundsSetMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/backgrounds/set', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1BackgroundsThumbnailMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/thumbnail', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1BackgroundsColorMapMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/color-map', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1BackgroundsSetLogoMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/backgrounds/set-logo', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1BackgroundsBpmMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/bpm', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1BackgroundsBpmMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/backgrounds/bpm', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1BackgroundsHueMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/backgrounds/hue', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1BackgroundsHueMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/backgrounds/hue', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getBackgroundsThemesMock = () => [
  getGetApiV1BackgroundsCurrentMockHandler(),
  getGetApiV1BackgroundsCurrentThemeMockHandler(),
  getGetApiV1BackgroundsThemesMockHandler(),
  getGetApiV1BackgroundsMockHandler(),
  getGetApiV1BackgroundsTagsMockHandler(),
  getPostApiV1BackgroundsSetMockHandler(),
  getGetApiV1BackgroundsThumbnailMockHandler(),
  getGetApiV1BackgroundsColorMapMockHandler(),
  getPostApiV1BackgroundsSetLogoMockHandler(),
  getGetApiV1BackgroundsBpmMockHandler(),
  getPostApiV1BackgroundsBpmMockHandler(),
  getGetApiV1BackgroundsHueMockHandler(),
  getPostApiV1BackgroundsHueMockHandler()
]
