/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiV1PlaylistsAddBody,
  PostApiV1PlaylistsLoadBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get the current lyrics playlist
 */
export type getApiV1PlaylistsLyricsResponse200 = {
  data: unknown
  status: 200
}

export type getApiV1PlaylistsLyricsResponseSuccess = (getApiV1PlaylistsLyricsResponse200) & {
  headers: Headers;
};
;

export type getApiV1PlaylistsLyricsResponse = (getApiV1PlaylistsLyricsResponseSuccess)

export const getGetApiV1PlaylistsLyricsUrl = () => {




  return `/api/v1/playlists/lyrics`
}

export const getApiV1PlaylistsLyrics = async ( options?: RequestInit): Promise<getApiV1PlaylistsLyricsResponse> => {

  return holyricsInstance<getApiV1PlaylistsLyricsResponse>(getGetApiV1PlaylistsLyricsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PlaylistsLyricsQueryKey = () => {
    return [
    `/api/v1/playlists/lyrics`
    ] as const;
    }


export const getGetApiV1PlaylistsLyricsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PlaylistsLyricsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>> = ({ signal }) => getApiV1PlaylistsLyrics({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PlaylistsLyricsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>>
export type GetApiV1PlaylistsLyricsQueryError = unknown


export function useGetApiV1PlaylistsLyrics<TData = Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlaylistsLyrics<TData = Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlaylistsLyrics<TData = Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PlaylistsLyrics<TData = Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsLyrics>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PlaylistsLyricsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get the current media playlist
 */
export type getApiV1PlaylistsMediaResponse200 = {
  data: unknown
  status: 200
}

export type getApiV1PlaylistsMediaResponseSuccess = (getApiV1PlaylistsMediaResponse200) & {
  headers: Headers;
};
;

export type getApiV1PlaylistsMediaResponse = (getApiV1PlaylistsMediaResponseSuccess)

export const getGetApiV1PlaylistsMediaUrl = () => {




  return `/api/v1/playlists/media`
}

export const getApiV1PlaylistsMedia = async ( options?: RequestInit): Promise<getApiV1PlaylistsMediaResponse> => {

  return holyricsInstance<getApiV1PlaylistsMediaResponse>(getGetApiV1PlaylistsMediaUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PlaylistsMediaQueryKey = () => {
    return [
    `/api/v1/playlists/media`
    ] as const;
    }


export const getGetApiV1PlaylistsMediaQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PlaylistsMediaQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>> = ({ signal }) => getApiV1PlaylistsMedia({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PlaylistsMediaQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>>
export type GetApiV1PlaylistsMediaQueryError = unknown


export function useGetApiV1PlaylistsMedia<TData = Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlaylistsMedia<TData = Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlaylistsMedia<TData = Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PlaylistsMedia<TData = Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsMedia>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PlaylistsMediaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Add an item to the playlist
 */
export type postApiV1PlaylistsAddResponse200 = {
  data: unknown
  status: 200
}

export type postApiV1PlaylistsAddResponseSuccess = (postApiV1PlaylistsAddResponse200) & {
  headers: Headers;
};
;

export type postApiV1PlaylistsAddResponse = (postApiV1PlaylistsAddResponseSuccess)

export const getPostApiV1PlaylistsAddUrl = () => {




  return `/api/v1/playlists/add`
}

export const postApiV1PlaylistsAdd = async (postApiV1PlaylistsAddBody: PostApiV1PlaylistsAddBody, options?: RequestInit): Promise<postApiV1PlaylistsAddResponse> => {

  return holyricsInstance<postApiV1PlaylistsAddResponse>(getPostApiV1PlaylistsAddUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PlaylistsAddBody,)
  }
);}




export const getPostApiV1PlaylistsAddMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlaylistsAdd>>, TError,{data: PostApiV1PlaylistsAddBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlaylistsAdd>>, TError,{data: PostApiV1PlaylistsAddBody}, TContext> => {

const mutationKey = ['postApiV1PlaylistsAdd'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PlaylistsAdd>>, {data: PostApiV1PlaylistsAddBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PlaylistsAdd(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PlaylistsAddMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PlaylistsAdd>>>
    export type PostApiV1PlaylistsAddMutationBody = PostApiV1PlaylistsAddBody
    export type PostApiV1PlaylistsAddMutationError = unknown

    export const usePostApiV1PlaylistsAdd = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlaylistsAdd>>, TError,{data: PostApiV1PlaylistsAddBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PlaylistsAdd>>,
        TError,
        {data: PostApiV1PlaylistsAddBody},
        TContext
      > => {
      return useMutation(getPostApiV1PlaylistsAddMutationOptions(options), queryClient);
    }
    /**
 * Get all saved playlists
 */
export type getApiV1PlaylistsSavedResponse200 = {
  data: unknown
  status: 200
}

export type getApiV1PlaylistsSavedResponseSuccess = (getApiV1PlaylistsSavedResponse200) & {
  headers: Headers;
};
;

export type getApiV1PlaylistsSavedResponse = (getApiV1PlaylistsSavedResponseSuccess)

export const getGetApiV1PlaylistsSavedUrl = () => {




  return `/api/v1/playlists/saved`
}

export const getApiV1PlaylistsSaved = async ( options?: RequestInit): Promise<getApiV1PlaylistsSavedResponse> => {

  return holyricsInstance<getApiV1PlaylistsSavedResponse>(getGetApiV1PlaylistsSavedUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1PlaylistsSavedQueryKey = () => {
    return [
    `/api/v1/playlists/saved`
    ] as const;
    }


export const getGetApiV1PlaylistsSavedQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PlaylistsSavedQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>> = ({ signal }) => getApiV1PlaylistsSaved({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PlaylistsSavedQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>>
export type GetApiV1PlaylistsSavedQueryError = unknown


export function useGetApiV1PlaylistsSaved<TData = Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlaylistsSaved<TData = Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PlaylistsSaved<TData = Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PlaylistsSaved<TData = Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PlaylistsSaved>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PlaylistsSavedQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Load a saved playlist
 */
export type postApiV1PlaylistsLoadResponse200 = {
  data: void
  status: 200
}

export type postApiV1PlaylistsLoadResponseSuccess = (postApiV1PlaylistsLoadResponse200) & {
  headers: Headers;
};
;

export type postApiV1PlaylistsLoadResponse = (postApiV1PlaylistsLoadResponseSuccess)

export const getPostApiV1PlaylistsLoadUrl = () => {




  return `/api/v1/playlists/load`
}

export const postApiV1PlaylistsLoad = async (postApiV1PlaylistsLoadBody: PostApiV1PlaylistsLoadBody, options?: RequestInit): Promise<postApiV1PlaylistsLoadResponse> => {

  return holyricsInstance<postApiV1PlaylistsLoadResponse>(getPostApiV1PlaylistsLoadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1PlaylistsLoadBody,)
  }
);}




export const getPostApiV1PlaylistsLoadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlaylistsLoad>>, TError,{data: PostApiV1PlaylistsLoadBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlaylistsLoad>>, TError,{data: PostApiV1PlaylistsLoadBody}, TContext> => {

const mutationKey = ['postApiV1PlaylistsLoad'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PlaylistsLoad>>, {data: PostApiV1PlaylistsLoadBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PlaylistsLoad(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PlaylistsLoadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PlaylistsLoad>>>
    export type PostApiV1PlaylistsLoadMutationBody = PostApiV1PlaylistsLoadBody
    export type PostApiV1PlaylistsLoadMutationError = unknown

    export const usePostApiV1PlaylistsLoad = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PlaylistsLoad>>, TError,{data: PostApiV1PlaylistsLoadBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PlaylistsLoad>>,
        TError,
        {data: PostApiV1PlaylistsLoadBody},
        TContext
      > => {
      return useMutation(getPostApiV1PlaylistsLoadMutationOptions(options), queryClient);
    }
