/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PostApiV1CrudCreateBody,
  PostApiV1CrudDeleteBody,
  PostApiV1CrudEditBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new item
 */
export type postApiV1CrudCreateResponse200 = {
  data: void
  status: 200
}

export type postApiV1CrudCreateResponseSuccess = (postApiV1CrudCreateResponse200) & {
  headers: Headers;
};
;

export type postApiV1CrudCreateResponse = (postApiV1CrudCreateResponseSuccess)

export const getPostApiV1CrudCreateUrl = () => {




  return `/api/v1/crud/create`
}

export const postApiV1CrudCreate = async (postApiV1CrudCreateBody: PostApiV1CrudCreateBody, options?: RequestInit): Promise<postApiV1CrudCreateResponse> => {

  return holyricsInstance<postApiV1CrudCreateResponse>(getPostApiV1CrudCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1CrudCreateBody,)
  }
);}




export const getPostApiV1CrudCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudCreate>>, TError,{data: PostApiV1CrudCreateBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudCreate>>, TError,{data: PostApiV1CrudCreateBody}, TContext> => {

const mutationKey = ['postApiV1CrudCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CrudCreate>>, {data: PostApiV1CrudCreateBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CrudCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CrudCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CrudCreate>>>
    export type PostApiV1CrudCreateMutationBody = PostApiV1CrudCreateBody
    export type PostApiV1CrudCreateMutationError = unknown

    export const usePostApiV1CrudCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudCreate>>, TError,{data: PostApiV1CrudCreateBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CrudCreate>>,
        TError,
        {data: PostApiV1CrudCreateBody},
        TContext
      > => {
      return useMutation(getPostApiV1CrudCreateMutationOptions(options), queryClient);
    }
    /**
 * Edit an existing item
 */
export type postApiV1CrudEditResponse200 = {
  data: void
  status: 200
}

export type postApiV1CrudEditResponseSuccess = (postApiV1CrudEditResponse200) & {
  headers: Headers;
};
;

export type postApiV1CrudEditResponse = (postApiV1CrudEditResponseSuccess)

export const getPostApiV1CrudEditUrl = () => {




  return `/api/v1/crud/edit`
}

export const postApiV1CrudEdit = async (postApiV1CrudEditBody: PostApiV1CrudEditBody, options?: RequestInit): Promise<postApiV1CrudEditResponse> => {

  return holyricsInstance<postApiV1CrudEditResponse>(getPostApiV1CrudEditUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1CrudEditBody,)
  }
);}




export const getPostApiV1CrudEditMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudEdit>>, TError,{data: PostApiV1CrudEditBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudEdit>>, TError,{data: PostApiV1CrudEditBody}, TContext> => {

const mutationKey = ['postApiV1CrudEdit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CrudEdit>>, {data: PostApiV1CrudEditBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CrudEdit(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CrudEditMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CrudEdit>>>
    export type PostApiV1CrudEditMutationBody = PostApiV1CrudEditBody
    export type PostApiV1CrudEditMutationError = unknown

    export const usePostApiV1CrudEdit = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudEdit>>, TError,{data: PostApiV1CrudEditBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CrudEdit>>,
        TError,
        {data: PostApiV1CrudEditBody},
        TContext
      > => {
      return useMutation(getPostApiV1CrudEditMutationOptions(options), queryClient);
    }
    /**
 * Delete an item
 */
export type postApiV1CrudDeleteResponse200 = {
  data: void
  status: 200
}

export type postApiV1CrudDeleteResponseSuccess = (postApiV1CrudDeleteResponse200) & {
  headers: Headers;
};
;

export type postApiV1CrudDeleteResponse = (postApiV1CrudDeleteResponseSuccess)

export const getPostApiV1CrudDeleteUrl = () => {




  return `/api/v1/crud/delete`
}

export const postApiV1CrudDelete = async (postApiV1CrudDeleteBody: PostApiV1CrudDeleteBody, options?: RequestInit): Promise<postApiV1CrudDeleteResponse> => {

  return holyricsInstance<postApiV1CrudDeleteResponse>(getPostApiV1CrudDeleteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1CrudDeleteBody,)
  }
);}




export const getPostApiV1CrudDeleteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudDelete>>, TError,{data: PostApiV1CrudDeleteBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudDelete>>, TError,{data: PostApiV1CrudDeleteBody}, TContext> => {

const mutationKey = ['postApiV1CrudDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1CrudDelete>>, {data: PostApiV1CrudDeleteBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1CrudDelete(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1CrudDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1CrudDelete>>>
    export type PostApiV1CrudDeleteMutationBody = PostApiV1CrudDeleteBody
    export type PostApiV1CrudDeleteMutationError = unknown

    export const usePostApiV1CrudDelete = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1CrudDelete>>, TError,{data: PostApiV1CrudDeleteBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1CrudDelete>>,
        TError,
        {data: PostApiV1CrudDeleteBody},
        TContext
      > => {
      return useMutation(getPostApiV1CrudDeleteMutationOptions(options), queryClient);
    }
