/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiV1QuickPresentationShowBody,
  PostApiV1QuickPresentationShowCountdownBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Show quick presentation text
 */
export type postApiV1QuickPresentationShowResponse200 = {
  data: void
  status: 200
}

export type postApiV1QuickPresentationShowResponseSuccess = (postApiV1QuickPresentationShowResponse200) & {
  headers: Headers;
};
;

export type postApiV1QuickPresentationShowResponse = (postApiV1QuickPresentationShowResponseSuccess)

export const getPostApiV1QuickPresentationShowUrl = () => {




  return `/api/v1/quick-presentation/show`
}

export const postApiV1QuickPresentationShow = async (postApiV1QuickPresentationShowBody: PostApiV1QuickPresentationShowBody, options?: RequestInit): Promise<postApiV1QuickPresentationShowResponse> => {

  return holyricsInstance<postApiV1QuickPresentationShowResponse>(getPostApiV1QuickPresentationShowUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1QuickPresentationShowBody,)
  }
);}




export const getPostApiV1QuickPresentationShowMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationShow>>, TError,{data: PostApiV1QuickPresentationShowBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationShow>>, TError,{data: PostApiV1QuickPresentationShowBody}, TContext> => {

const mutationKey = ['postApiV1QuickPresentationShow'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuickPresentationShow>>, {data: PostApiV1QuickPresentationShowBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1QuickPresentationShow(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuickPresentationShowMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuickPresentationShow>>>
    export type PostApiV1QuickPresentationShowMutationBody = PostApiV1QuickPresentationShowBody
    export type PostApiV1QuickPresentationShowMutationError = unknown

    export const usePostApiV1QuickPresentationShow = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationShow>>, TError,{data: PostApiV1QuickPresentationShowBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuickPresentationShow>>,
        TError,
        {data: PostApiV1QuickPresentationShowBody},
        TContext
      > => {
      return useMutation(getPostApiV1QuickPresentationShowMutationOptions(options), queryClient);
    }
    /**
 * Show countdown
 */
export type postApiV1QuickPresentationShowCountdownResponse200 = {
  data: void
  status: 200
}

export type postApiV1QuickPresentationShowCountdownResponseSuccess = (postApiV1QuickPresentationShowCountdownResponse200) & {
  headers: Headers;
};
;

export type postApiV1QuickPresentationShowCountdownResponse = (postApiV1QuickPresentationShowCountdownResponseSuccess)

export const getPostApiV1QuickPresentationShowCountdownUrl = () => {




  return `/api/v1/quick-presentation/show-countdown`
}

export const postApiV1QuickPresentationShowCountdown = async (postApiV1QuickPresentationShowCountdownBody: PostApiV1QuickPresentationShowCountdownBody, options?: RequestInit): Promise<postApiV1QuickPresentationShowCountdownResponse> => {

  return holyricsInstance<postApiV1QuickPresentationShowCountdownResponse>(getPostApiV1QuickPresentationShowCountdownUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1QuickPresentationShowCountdownBody,)
  }
);}




export const getPostApiV1QuickPresentationShowCountdownMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationShowCountdown>>, TError,{data: PostApiV1QuickPresentationShowCountdownBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationShowCountdown>>, TError,{data: PostApiV1QuickPresentationShowCountdownBody}, TContext> => {

const mutationKey = ['postApiV1QuickPresentationShowCountdown'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuickPresentationShowCountdown>>, {data: PostApiV1QuickPresentationShowCountdownBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1QuickPresentationShowCountdown(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuickPresentationShowCountdownMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuickPresentationShowCountdown>>>
    export type PostApiV1QuickPresentationShowCountdownMutationBody = PostApiV1QuickPresentationShowCountdownBody
    export type PostApiV1QuickPresentationShowCountdownMutationError = unknown

    export const usePostApiV1QuickPresentationShowCountdown = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationShowCountdown>>, TError,{data: PostApiV1QuickPresentationShowCountdownBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuickPresentationShowCountdown>>,
        TError,
        {data: PostApiV1QuickPresentationShowCountdownBody},
        TContext
      > => {
      return useMutation(getPostApiV1QuickPresentationShowCountdownMutationOptions(options), queryClient);
    }
    /**
 * Next slide in quick presentation
 */
export type postApiV1QuickPresentationNextResponse200 = {
  data: void
  status: 200
}

export type postApiV1QuickPresentationNextResponseSuccess = (postApiV1QuickPresentationNextResponse200) & {
  headers: Headers;
};
;

export type postApiV1QuickPresentationNextResponse = (postApiV1QuickPresentationNextResponseSuccess)

export const getPostApiV1QuickPresentationNextUrl = () => {




  return `/api/v1/quick-presentation/next`
}

export const postApiV1QuickPresentationNext = async ( options?: RequestInit): Promise<postApiV1QuickPresentationNextResponse> => {

  return holyricsInstance<postApiV1QuickPresentationNextResponse>(getPostApiV1QuickPresentationNextUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1QuickPresentationNextMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationNext>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationNext>>, TError,void, TContext> => {

const mutationKey = ['postApiV1QuickPresentationNext'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuickPresentationNext>>, void> = () => {


          return  postApiV1QuickPresentationNext(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuickPresentationNextMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuickPresentationNext>>>

    export type PostApiV1QuickPresentationNextMutationError = unknown

    export const usePostApiV1QuickPresentationNext = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationNext>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuickPresentationNext>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1QuickPresentationNextMutationOptions(options), queryClient);
    }
    /**
 * Previous slide in quick presentation
 */
export type postApiV1QuickPresentationPreviousResponse200 = {
  data: void
  status: 200
}

export type postApiV1QuickPresentationPreviousResponseSuccess = (postApiV1QuickPresentationPreviousResponse200) & {
  headers: Headers;
};
;

export type postApiV1QuickPresentationPreviousResponse = (postApiV1QuickPresentationPreviousResponseSuccess)

export const getPostApiV1QuickPresentationPreviousUrl = () => {




  return `/api/v1/quick-presentation/previous`
}

export const postApiV1QuickPresentationPrevious = async ( options?: RequestInit): Promise<postApiV1QuickPresentationPreviousResponse> => {

  return holyricsInstance<postApiV1QuickPresentationPreviousResponse>(getPostApiV1QuickPresentationPreviousUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1QuickPresentationPreviousMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationPrevious>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationPrevious>>, TError,void, TContext> => {

const mutationKey = ['postApiV1QuickPresentationPrevious'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuickPresentationPrevious>>, void> = () => {


          return  postApiV1QuickPresentationPrevious(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuickPresentationPreviousMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuickPresentationPrevious>>>

    export type PostApiV1QuickPresentationPreviousMutationError = unknown

    export const usePostApiV1QuickPresentationPrevious = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationPrevious>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuickPresentationPrevious>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1QuickPresentationPreviousMutationOptions(options), queryClient);
    }
    /**
 * Close quick presentation
 */
export type postApiV1QuickPresentationCloseResponse200 = {
  data: void
  status: 200
}

export type postApiV1QuickPresentationCloseResponseSuccess = (postApiV1QuickPresentationCloseResponse200) & {
  headers: Headers;
};
;

export type postApiV1QuickPresentationCloseResponse = (postApiV1QuickPresentationCloseResponseSuccess)

export const getPostApiV1QuickPresentationCloseUrl = () => {




  return `/api/v1/quick-presentation/close`
}

export const postApiV1QuickPresentationClose = async ( options?: RequestInit): Promise<postApiV1QuickPresentationCloseResponse> => {

  return holyricsInstance<postApiV1QuickPresentationCloseResponse>(getPostApiV1QuickPresentationCloseUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1QuickPresentationCloseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationClose>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationClose>>, TError,void, TContext> => {

const mutationKey = ['postApiV1QuickPresentationClose'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1QuickPresentationClose>>, void> = () => {


          return  postApiV1QuickPresentationClose(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1QuickPresentationCloseMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1QuickPresentationClose>>>

    export type PostApiV1QuickPresentationCloseMutationError = unknown

    export const usePostApiV1QuickPresentationClose = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1QuickPresentationClose>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1QuickPresentationClose>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1QuickPresentationCloseMutationOptions(options), queryClient);
    }
    /**
 * Get current quick presentation info
 */
export type getApiV1QuickPresentationCurrentResponse200 = {
  data: void
  status: 200
}

export type getApiV1QuickPresentationCurrentResponseSuccess = (getApiV1QuickPresentationCurrentResponse200) & {
  headers: Headers;
};
;

export type getApiV1QuickPresentationCurrentResponse = (getApiV1QuickPresentationCurrentResponseSuccess)

export const getGetApiV1QuickPresentationCurrentUrl = () => {




  return `/api/v1/quick-presentation/current`
}

export const getApiV1QuickPresentationCurrent = async ( options?: RequestInit): Promise<getApiV1QuickPresentationCurrentResponse> => {

  return holyricsInstance<getApiV1QuickPresentationCurrentResponse>(getGetApiV1QuickPresentationCurrentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1QuickPresentationCurrentQueryKey = () => {
    return [
    `/api/v1/quick-presentation/current`
    ] as const;
    }


export const getGetApiV1QuickPresentationCurrentQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1QuickPresentationCurrentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>> = ({ signal }) => getApiV1QuickPresentationCurrent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1QuickPresentationCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>>
export type GetApiV1QuickPresentationCurrentQueryError = unknown


export function useGetApiV1QuickPresentationCurrent<TData = Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1QuickPresentationCurrent<TData = Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1QuickPresentationCurrent<TData = Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1QuickPresentationCurrent<TData = Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1QuickPresentationCurrent>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1QuickPresentationCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






