/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Holyrics Control Server API
 * API for controlling Holyrics remotely
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV1SystemConnectionStatus200,
  PostApiV1SystemCheckPermissionsBody,
  PostApiV1SystemRuntimeEnvironmentBody
} from '../model';

import { holyricsInstance } from '../../../lib/holyrics-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get token info
 */
export type getApiV1SystemTokenInfoResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemTokenInfoResponseSuccess = (getApiV1SystemTokenInfoResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemTokenInfoResponse = (getApiV1SystemTokenInfoResponseSuccess)

export const getGetApiV1SystemTokenInfoUrl = () => {




  return `/api/v1/system/token-info`
}

export const getApiV1SystemTokenInfo = async ( options?: RequestInit): Promise<getApiV1SystemTokenInfoResponse> => {

  return holyricsInstance<getApiV1SystemTokenInfoResponse>(getGetApiV1SystemTokenInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemTokenInfoQueryKey = () => {
    return [
    `/api/v1/system/token-info`
    ] as const;
    }


export const getGetApiV1SystemTokenInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemTokenInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>> = ({ signal }) => getApiV1SystemTokenInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemTokenInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>>
export type GetApiV1SystemTokenInfoQueryError = unknown


export function useGetApiV1SystemTokenInfo<TData = Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemTokenInfo<TData = Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemTokenInfo<TData = Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemTokenInfo<TData = Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemTokenInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemTokenInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Check permissions
 */
export type postApiV1SystemCheckPermissionsResponse200 = {
  data: void
  status: 200
}

export type postApiV1SystemCheckPermissionsResponseSuccess = (postApiV1SystemCheckPermissionsResponse200) & {
  headers: Headers;
};
;

export type postApiV1SystemCheckPermissionsResponse = (postApiV1SystemCheckPermissionsResponseSuccess)

export const getPostApiV1SystemCheckPermissionsUrl = () => {




  return `/api/v1/system/check-permissions`
}

export const postApiV1SystemCheckPermissions = async (postApiV1SystemCheckPermissionsBody: PostApiV1SystemCheckPermissionsBody, options?: RequestInit): Promise<postApiV1SystemCheckPermissionsResponse> => {

  return holyricsInstance<postApiV1SystemCheckPermissionsResponse>(getPostApiV1SystemCheckPermissionsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SystemCheckPermissionsBody,)
  }
);}




export const getPostApiV1SystemCheckPermissionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemCheckPermissions>>, TError,{data: PostApiV1SystemCheckPermissionsBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemCheckPermissions>>, TError,{data: PostApiV1SystemCheckPermissionsBody}, TContext> => {

const mutationKey = ['postApiV1SystemCheckPermissions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SystemCheckPermissions>>, {data: PostApiV1SystemCheckPermissionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SystemCheckPermissions(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SystemCheckPermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SystemCheckPermissions>>>
    export type PostApiV1SystemCheckPermissionsMutationBody = PostApiV1SystemCheckPermissionsBody
    export type PostApiV1SystemCheckPermissionsMutationError = unknown

    export const usePostApiV1SystemCheckPermissions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemCheckPermissions>>, TError,{data: PostApiV1SystemCheckPermissionsBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SystemCheckPermissions>>,
        TError,
        {data: PostApiV1SystemCheckPermissionsBody},
        TContext
      > => {
      return useMutation(getPostApiV1SystemCheckPermissionsMutationOptions(options), queryClient);
    }
    /**
 * Get Holyrics version
 */
export type getApiV1SystemVersionResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemVersionResponseSuccess = (getApiV1SystemVersionResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemVersionResponse = (getApiV1SystemVersionResponseSuccess)

export const getGetApiV1SystemVersionUrl = () => {




  return `/api/v1/system/version`
}

export const getApiV1SystemVersion = async ( options?: RequestInit): Promise<getApiV1SystemVersionResponse> => {

  return holyricsInstance<getApiV1SystemVersionResponse>(getGetApiV1SystemVersionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemVersionQueryKey = () => {
    return [
    `/api/v1/system/version`
    ] as const;
    }


export const getGetApiV1SystemVersionQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemVersionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemVersion>>> = ({ signal }) => getApiV1SystemVersion({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemVersionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemVersion>>>
export type GetApiV1SystemVersionQueryError = unknown


export function useGetApiV1SystemVersion<TData = Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemVersion>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemVersion<TData = Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemVersion>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemVersion<TData = Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemVersion<TData = Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemVersion>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemVersionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get Holyrics plan info
 */
export type getApiV1SystemPlanInfoResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemPlanInfoResponseSuccess = (getApiV1SystemPlanInfoResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemPlanInfoResponse = (getApiV1SystemPlanInfoResponseSuccess)

export const getGetApiV1SystemPlanInfoUrl = () => {




  return `/api/v1/system/plan-info`
}

export const getApiV1SystemPlanInfo = async ( options?: RequestInit): Promise<getApiV1SystemPlanInfoResponse> => {

  return holyricsInstance<getApiV1SystemPlanInfoResponse>(getGetApiV1SystemPlanInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemPlanInfoQueryKey = () => {
    return [
    `/api/v1/system/plan-info`
    ] as const;
    }


export const getGetApiV1SystemPlanInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemPlanInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>> = ({ signal }) => getApiV1SystemPlanInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemPlanInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>>
export type GetApiV1SystemPlanInfoQueryError = unknown


export function useGetApiV1SystemPlanInfo<TData = Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemPlanInfo<TData = Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemPlanInfo<TData = Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemPlanInfo<TData = Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemPlanInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemPlanInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get API server info
 */
export type getApiV1SystemApiServerInfoResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemApiServerInfoResponseSuccess = (getApiV1SystemApiServerInfoResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemApiServerInfoResponse = (getApiV1SystemApiServerInfoResponseSuccess)

export const getGetApiV1SystemApiServerInfoUrl = () => {




  return `/api/v1/system/api-server-info`
}

export const getApiV1SystemApiServerInfo = async ( options?: RequestInit): Promise<getApiV1SystemApiServerInfoResponse> => {

  return holyricsInstance<getApiV1SystemApiServerInfoResponse>(getGetApiV1SystemApiServerInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemApiServerInfoQueryKey = () => {
    return [
    `/api/v1/system/api-server-info`
    ] as const;
    }


export const getGetApiV1SystemApiServerInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemApiServerInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>> = ({ signal }) => getApiV1SystemApiServerInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemApiServerInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>>
export type GetApiV1SystemApiServerInfoQueryError = unknown


export function useGetApiV1SystemApiServerInfo<TData = Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemApiServerInfo<TData = Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemApiServerInfo<TData = Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemApiServerInfo<TData = Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApiServerInfo>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemApiServerInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get runtime environment
 */
export type getApiV1SystemRuntimeEnvironmentResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemRuntimeEnvironmentResponseSuccess = (getApiV1SystemRuntimeEnvironmentResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemRuntimeEnvironmentResponse = (getApiV1SystemRuntimeEnvironmentResponseSuccess)

export const getGetApiV1SystemRuntimeEnvironmentUrl = () => {




  return `/api/v1/system/runtime-environment`
}

export const getApiV1SystemRuntimeEnvironment = async ( options?: RequestInit): Promise<getApiV1SystemRuntimeEnvironmentResponse> => {

  return holyricsInstance<getApiV1SystemRuntimeEnvironmentResponse>(getGetApiV1SystemRuntimeEnvironmentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemRuntimeEnvironmentQueryKey = () => {
    return [
    `/api/v1/system/runtime-environment`
    ] as const;
    }


export const getGetApiV1SystemRuntimeEnvironmentQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemRuntimeEnvironmentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>> = ({ signal }) => getApiV1SystemRuntimeEnvironment({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemRuntimeEnvironmentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>>
export type GetApiV1SystemRuntimeEnvironmentQueryError = unknown


export function useGetApiV1SystemRuntimeEnvironment<TData = Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemRuntimeEnvironment<TData = Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemRuntimeEnvironment<TData = Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemRuntimeEnvironment<TData = Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemRuntimeEnvironment>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemRuntimeEnvironmentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set runtime environment
 */
export type postApiV1SystemRuntimeEnvironmentResponse200 = {
  data: void
  status: 200
}

export type postApiV1SystemRuntimeEnvironmentResponseSuccess = (postApiV1SystemRuntimeEnvironmentResponse200) & {
  headers: Headers;
};
;

export type postApiV1SystemRuntimeEnvironmentResponse = (postApiV1SystemRuntimeEnvironmentResponseSuccess)

export const getPostApiV1SystemRuntimeEnvironmentUrl = () => {




  return `/api/v1/system/runtime-environment`
}

export const postApiV1SystemRuntimeEnvironment = async (postApiV1SystemRuntimeEnvironmentBody: PostApiV1SystemRuntimeEnvironmentBody, options?: RequestInit): Promise<postApiV1SystemRuntimeEnvironmentResponse> => {

  return holyricsInstance<postApiV1SystemRuntimeEnvironmentResponse>(getPostApiV1SystemRuntimeEnvironmentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SystemRuntimeEnvironmentBody,)
  }
);}




export const getPostApiV1SystemRuntimeEnvironmentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemRuntimeEnvironment>>, TError,{data: PostApiV1SystemRuntimeEnvironmentBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemRuntimeEnvironment>>, TError,{data: PostApiV1SystemRuntimeEnvironmentBody}, TContext> => {

const mutationKey = ['postApiV1SystemRuntimeEnvironment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SystemRuntimeEnvironment>>, {data: PostApiV1SystemRuntimeEnvironmentBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SystemRuntimeEnvironment(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SystemRuntimeEnvironmentMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SystemRuntimeEnvironment>>>
    export type PostApiV1SystemRuntimeEnvironmentMutationBody = PostApiV1SystemRuntimeEnvironmentBody
    export type PostApiV1SystemRuntimeEnvironmentMutationError = unknown

    export const usePostApiV1SystemRuntimeEnvironment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemRuntimeEnvironment>>, TError,{data: PostApiV1SystemRuntimeEnvironmentBody}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SystemRuntimeEnvironment>>,
        TError,
        {data: PostApiV1SystemRuntimeEnvironmentBody},
        TContext
      > => {
      return useMutation(getPostApiV1SystemRuntimeEnvironmentMutationOptions(options), queryClient);
    }
    /**
 * Get global settings
 */
export type getApiV1SystemGlobalSettingsResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemGlobalSettingsResponseSuccess = (getApiV1SystemGlobalSettingsResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemGlobalSettingsResponse = (getApiV1SystemGlobalSettingsResponseSuccess)

export const getGetApiV1SystemGlobalSettingsUrl = () => {




  return `/api/v1/system/global-settings`
}

export const getApiV1SystemGlobalSettings = async ( options?: RequestInit): Promise<getApiV1SystemGlobalSettingsResponse> => {

  return holyricsInstance<getApiV1SystemGlobalSettingsResponse>(getGetApiV1SystemGlobalSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemGlobalSettingsQueryKey = () => {
    return [
    `/api/v1/system/global-settings`
    ] as const;
    }


export const getGetApiV1SystemGlobalSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemGlobalSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>> = ({ signal }) => getApiV1SystemGlobalSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemGlobalSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>>
export type GetApiV1SystemGlobalSettingsQueryError = unknown


export function useGetApiV1SystemGlobalSettings<TData = Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemGlobalSettings<TData = Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemGlobalSettings<TData = Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemGlobalSettings<TData = Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemGlobalSettings>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemGlobalSettingsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set global settings
 */
export type postApiV1SystemGlobalSettingsResponse200 = {
  data: void
  status: 200
}

export type postApiV1SystemGlobalSettingsResponseSuccess = (postApiV1SystemGlobalSettingsResponse200) & {
  headers: Headers;
};
;

export type postApiV1SystemGlobalSettingsResponse = (postApiV1SystemGlobalSettingsResponseSuccess)

export const getPostApiV1SystemGlobalSettingsUrl = () => {




  return `/api/v1/system/global-settings`
}

export const postApiV1SystemGlobalSettings = async (postApiV1SystemGlobalSettingsBody: unknown, options?: RequestInit): Promise<postApiV1SystemGlobalSettingsResponse> => {

  return holyricsInstance<postApiV1SystemGlobalSettingsResponse>(getPostApiV1SystemGlobalSettingsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SystemGlobalSettingsBody,)
  }
);}




export const getPostApiV1SystemGlobalSettingsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemGlobalSettings>>, TError,{data: unknown}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemGlobalSettings>>, TError,{data: unknown}, TContext> => {

const mutationKey = ['postApiV1SystemGlobalSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SystemGlobalSettings>>, {data: unknown}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SystemGlobalSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SystemGlobalSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SystemGlobalSettings>>>
    export type PostApiV1SystemGlobalSettingsMutationBody = unknown
    export type PostApiV1SystemGlobalSettingsMutationError = unknown

    export const usePostApiV1SystemGlobalSettings = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemGlobalSettings>>, TError,{data: unknown}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SystemGlobalSettings>>,
        TError,
        {data: unknown},
        TContext
      > => {
      return useMutation(getPostApiV1SystemGlobalSettingsMutationOptions(options), queryClient);
    }
    /**
 * Get sync status
 */
export type getApiV1SystemSyncStatusResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemSyncStatusResponseSuccess = (getApiV1SystemSyncStatusResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemSyncStatusResponse = (getApiV1SystemSyncStatusResponseSuccess)

export const getGetApiV1SystemSyncStatusUrl = () => {




  return `/api/v1/system/sync-status`
}

export const getApiV1SystemSyncStatus = async ( options?: RequestInit): Promise<getApiV1SystemSyncStatusResponse> => {

  return holyricsInstance<getApiV1SystemSyncStatusResponse>(getGetApiV1SystemSyncStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemSyncStatusQueryKey = () => {
    return [
    `/api/v1/system/sync-status`
    ] as const;
    }


export const getGetApiV1SystemSyncStatusQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemSyncStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>> = ({ signal }) => getApiV1SystemSyncStatus({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemSyncStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>>
export type GetApiV1SystemSyncStatusQueryError = unknown


export function useGetApiV1SystemSyncStatus<TData = Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemSyncStatus<TData = Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemSyncStatus<TData = Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemSyncStatus<TData = Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemSyncStatus>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemSyncStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get configured APIs
 */
export type getApiV1SystemApisResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemApisResponseSuccess = (getApiV1SystemApisResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemApisResponse = (getApiV1SystemApisResponseSuccess)

export const getGetApiV1SystemApisUrl = () => {




  return `/api/v1/system/apis`
}

export const getApiV1SystemApis = async ( options?: RequestInit): Promise<getApiV1SystemApisResponse> => {

  return holyricsInstance<getApiV1SystemApisResponse>(getGetApiV1SystemApisUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemApisQueryKey = () => {
    return [
    `/api/v1/system/apis`
    ] as const;
    }


export const getGetApiV1SystemApisQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemApis>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApis>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemApisQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemApis>>> = ({ signal }) => getApiV1SystemApis({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApis>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemApisQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemApis>>>
export type GetApiV1SystemApisQueryError = unknown


export function useGetApiV1SystemApis<TData = Awaited<ReturnType<typeof getApiV1SystemApis>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApis>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemApis>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemApis>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemApis<TData = Awaited<ReturnType<typeof getApiV1SystemApis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApis>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemApis>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemApis>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemApis<TData = Awaited<ReturnType<typeof getApiV1SystemApis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApis>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemApis<TData = Awaited<ReturnType<typeof getApiV1SystemApis>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemApis>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemApisQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get scripts
 */
export type getApiV1SystemScriptsResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemScriptsResponseSuccess = (getApiV1SystemScriptsResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemScriptsResponse = (getApiV1SystemScriptsResponseSuccess)

export const getGetApiV1SystemScriptsUrl = () => {




  return `/api/v1/system/scripts`
}

export const getApiV1SystemScripts = async ( options?: RequestInit): Promise<getApiV1SystemScriptsResponse> => {

  return holyricsInstance<getApiV1SystemScriptsResponse>(getGetApiV1SystemScriptsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemScriptsQueryKey = () => {
    return [
    `/api/v1/system/scripts`
    ] as const;
    }


export const getGetApiV1SystemScriptsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemScriptsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemScripts>>> = ({ signal }) => getApiV1SystemScripts({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemScriptsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemScripts>>>
export type GetApiV1SystemScriptsQueryError = unknown


export function useGetApiV1SystemScripts<TData = Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemScripts>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemScripts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemScripts<TData = Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemScripts>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemScripts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemScripts<TData = Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemScripts<TData = Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemScripts>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemScriptsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get modules
 */
export type getApiV1SystemModulesResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemModulesResponseSuccess = (getApiV1SystemModulesResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemModulesResponse = (getApiV1SystemModulesResponseSuccess)

export const getGetApiV1SystemModulesUrl = () => {




  return `/api/v1/system/modules`
}

export const getApiV1SystemModules = async ( options?: RequestInit): Promise<getApiV1SystemModulesResponse> => {

  return holyricsInstance<getApiV1SystemModulesResponse>(getGetApiV1SystemModulesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemModulesQueryKey = () => {
    return [
    `/api/v1/system/modules`
    ] as const;
    }


export const getGetApiV1SystemModulesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemModules>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemModules>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemModulesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemModules>>> = ({ signal }) => getApiV1SystemModules({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemModules>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemModulesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemModules>>>
export type GetApiV1SystemModulesQueryError = unknown


export function useGetApiV1SystemModules<TData = Awaited<ReturnType<typeof getApiV1SystemModules>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemModules>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemModules>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemModules<TData = Awaited<ReturnType<typeof getApiV1SystemModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemModules>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemModules>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemModules>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemModules<TData = Awaited<ReturnType<typeof getApiV1SystemModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemModules>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemModules<TData = Awaited<ReturnType<typeof getApiV1SystemModules>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemModules>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemModulesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get interface input status
 */
export type getApiV1SystemInterfaceInputResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemInterfaceInputResponseSuccess = (getApiV1SystemInterfaceInputResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemInterfaceInputResponse = (getApiV1SystemInterfaceInputResponseSuccess)

export const getGetApiV1SystemInterfaceInputUrl = () => {




  return `/api/v1/system/interface-input`
}

export const getApiV1SystemInterfaceInput = async ( options?: RequestInit): Promise<getApiV1SystemInterfaceInputResponse> => {

  return holyricsInstance<getApiV1SystemInterfaceInputResponse>(getGetApiV1SystemInterfaceInputUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemInterfaceInputQueryKey = () => {
    return [
    `/api/v1/system/interface-input`
    ] as const;
    }


export const getGetApiV1SystemInterfaceInputQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemInterfaceInputQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>> = ({ signal }) => getApiV1SystemInterfaceInput({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemInterfaceInputQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>>
export type GetApiV1SystemInterfaceInputQueryError = unknown


export function useGetApiV1SystemInterfaceInput<TData = Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemInterfaceInput<TData = Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemInterfaceInput<TData = Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemInterfaceInput<TData = Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemInterfaceInput>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemInterfaceInputQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Set interface input status
 */
export type postApiV1SystemInterfaceInputResponse200 = {
  data: void
  status: 200
}

export type postApiV1SystemInterfaceInputResponseSuccess = (postApiV1SystemInterfaceInputResponse200) & {
  headers: Headers;
};
;

export type postApiV1SystemInterfaceInputResponse = (postApiV1SystemInterfaceInputResponseSuccess)

export const getPostApiV1SystemInterfaceInputUrl = () => {




  return `/api/v1/system/interface-input`
}

export const postApiV1SystemInterfaceInput = async (postApiV1SystemInterfaceInputBody: unknown, options?: RequestInit): Promise<postApiV1SystemInterfaceInputResponse> => {

  return holyricsInstance<postApiV1SystemInterfaceInputResponse>(getPostApiV1SystemInterfaceInputUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiV1SystemInterfaceInputBody,)
  }
);}




export const getPostApiV1SystemInterfaceInputMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemInterfaceInput>>, TError,{data: unknown}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemInterfaceInput>>, TError,{data: unknown}, TContext> => {

const mutationKey = ['postApiV1SystemInterfaceInput'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SystemInterfaceInput>>, {data: unknown}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1SystemInterfaceInput(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SystemInterfaceInputMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SystemInterfaceInput>>>
    export type PostApiV1SystemInterfaceInputMutationBody = unknown
    export type PostApiV1SystemInterfaceInputMutationError = unknown

    export const usePostApiV1SystemInterfaceInput = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemInterfaceInput>>, TError,{data: unknown}, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SystemInterfaceInput>>,
        TError,
        {data: unknown},
        TContext
      > => {
      return useMutation(getPostApiV1SystemInterfaceInputMutationOptions(options), queryClient);
    }
    /**
 * Open draw lots window
 */
export type postApiV1SystemOpenDrawLotsResponse200 = {
  data: void
  status: 200
}

export type postApiV1SystemOpenDrawLotsResponseSuccess = (postApiV1SystemOpenDrawLotsResponse200) & {
  headers: Headers;
};
;

export type postApiV1SystemOpenDrawLotsResponse = (postApiV1SystemOpenDrawLotsResponseSuccess)

export const getPostApiV1SystemOpenDrawLotsUrl = () => {




  return `/api/v1/system/open-draw-lots`
}

export const postApiV1SystemOpenDrawLots = async ( options?: RequestInit): Promise<postApiV1SystemOpenDrawLotsResponse> => {

  return holyricsInstance<postApiV1SystemOpenDrawLotsResponse>(getPostApiV1SystemOpenDrawLotsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiV1SystemOpenDrawLotsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemOpenDrawLots>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemOpenDrawLots>>, TError,void, TContext> => {

const mutationKey = ['postApiV1SystemOpenDrawLots'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SystemOpenDrawLots>>, void> = () => {


          return  postApiV1SystemOpenDrawLots(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SystemOpenDrawLotsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SystemOpenDrawLots>>>

    export type PostApiV1SystemOpenDrawLotsMutationError = unknown

    export const usePostApiV1SystemOpenDrawLots = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SystemOpenDrawLots>>, TError,void, TContext>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SystemOpenDrawLots>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiV1SystemOpenDrawLotsMutationOptions(options), queryClient);
    }
    /**
 * Get styled models
 */
export type getApiV1SystemStyledModelsResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemStyledModelsResponseSuccess = (getApiV1SystemStyledModelsResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemStyledModelsResponse = (getApiV1SystemStyledModelsResponseSuccess)

export const getGetApiV1SystemStyledModelsUrl = () => {




  return `/api/v1/system/styled-models`
}

export const getApiV1SystemStyledModels = async ( options?: RequestInit): Promise<getApiV1SystemStyledModelsResponse> => {

  return holyricsInstance<getApiV1SystemStyledModelsResponse>(getGetApiV1SystemStyledModelsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemStyledModelsQueryKey = () => {
    return [
    `/api/v1/system/styled-models`
    ] as const;
    }


export const getGetApiV1SystemStyledModelsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemStyledModelsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemStyledModels>>> = ({ signal }) => getApiV1SystemStyledModels({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemStyledModelsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemStyledModels>>>
export type GetApiV1SystemStyledModelsQueryError = unknown


export function useGetApiV1SystemStyledModels<TData = Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemStyledModels>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemStyledModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemStyledModels<TData = Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemStyledModels>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemStyledModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemStyledModels<TData = Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemStyledModels<TData = Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModels>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemStyledModelsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get styled models as map
 */
export type getApiV1SystemStyledModelsMapResponse200 = {
  data: void
  status: 200
}

export type getApiV1SystemStyledModelsMapResponseSuccess = (getApiV1SystemStyledModelsMapResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemStyledModelsMapResponse = (getApiV1SystemStyledModelsMapResponseSuccess)

export const getGetApiV1SystemStyledModelsMapUrl = () => {




  return `/api/v1/system/styled-models/map`
}

export const getApiV1SystemStyledModelsMap = async ( options?: RequestInit): Promise<getApiV1SystemStyledModelsMapResponse> => {

  return holyricsInstance<getApiV1SystemStyledModelsMapResponse>(getGetApiV1SystemStyledModelsMapUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemStyledModelsMapQueryKey = () => {
    return [
    `/api/v1/system/styled-models/map`
    ] as const;
    }


export const getGetApiV1SystemStyledModelsMapQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemStyledModelsMapQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>> = ({ signal }) => getApiV1SystemStyledModelsMap({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemStyledModelsMapQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>>
export type GetApiV1SystemStyledModelsMapQueryError = unknown


export function useGetApiV1SystemStyledModelsMap<TData = Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemStyledModelsMap<TData = Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemStyledModelsMap<TData = Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemStyledModelsMap<TData = Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemStyledModelsMap>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemStyledModelsMapQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Get connection status to Holyrics
 */
export type getApiV1SystemConnectionStatusResponse200 = {
  data: GetApiV1SystemConnectionStatus200
  status: 200
}

export type getApiV1SystemConnectionStatusResponseSuccess = (getApiV1SystemConnectionStatusResponse200) & {
  headers: Headers;
};
;

export type getApiV1SystemConnectionStatusResponse = (getApiV1SystemConnectionStatusResponseSuccess)

export const getGetApiV1SystemConnectionStatusUrl = () => {




  return `/api/v1/system/connection-status`
}

export const getApiV1SystemConnectionStatus = async ( options?: RequestInit): Promise<getApiV1SystemConnectionStatusResponse> => {

  return holyricsInstance<getApiV1SystemConnectionStatusResponse>(getGetApiV1SystemConnectionStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiV1SystemConnectionStatusQueryKey = () => {
    return [
    `/api/v1/system/connection-status`
    ] as const;
    }


export const getGetApiV1SystemConnectionStatusQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1SystemConnectionStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>> = ({ signal }) => getApiV1SystemConnectionStatus({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1SystemConnectionStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>>
export type GetApiV1SystemConnectionStatusQueryError = unknown


export function useGetApiV1SystemConnectionStatus<TData = Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemConnectionStatus<TData = Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1SystemConnectionStatus<TData = Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1SystemConnectionStatus<TData = Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1SystemConnectionStatus>>, TError, TData>>, request?: SecondParameter<typeof holyricsInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1SystemConnectionStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






